import tiersJson from "./informationTiersV160.json";
import questionsJson from "./homeQuestionsV160.json";
import type { DisplayTypeV159 } from "./specTypesV159";

/**
 * V160 core-first: which datasets a reader meets first.
 *
 * Both JSON files are generated by scripts/v160/build-core-first-v160.mjs
 * from the V160 plan; the tier of an element is never written in code.
 * core = shown by default, support/reference = on '전체 보기' and in search,
 * hidden = the ⓪ status elements (excluded or not yet delivered).
 */
export type InformationTierV160 = "core" | "support" | "reference" | "hidden";

export interface InformationTierRowV160 {
  elementId: string;
  tier: InformationTierV160;
  displayType: DisplayTypeV159;
  reason: string;
}

export interface HomeQuestionV160 {
  displayType: DisplayTypeV159;
  title: string;
  description: string;
  coreElementIds: string[];
  /** The card-summary headline shown on the question card; null = no KPI. */
  heroIndicator: { elementId: string; requested: string; source: string } | null;
}

export const TIER_LABELS_V160: Record<InformationTierV160, string> = {
  core: "핵심",
  support: "보조",
  reference: "참고",
  hidden: "비공개",
};

const TIERS_V160 = new Map<string, InformationTierRowV160>(
  (tiersJson.rows as InformationTierRowV160[]).map((row) => [row.elementId, row])
);

export function getTierV160(elementId: string): InformationTierV160 | null {
  return TIERS_V160.get(elementId.toUpperCase())?.tier ?? null;
}

export function allTiersV160(): InformationTierRowV160[] {
  return [...TIERS_V160.values()];
}

export const HOME_QUESTIONS_V160: readonly HomeQuestionV160[] = (questionsJson.questions as HomeQuestionV160[]).map(
  ({ displayType, title, description, coreElementIds, heroIndicator }) => ({ displayType, title, description, coreElementIds, heroIndicator })
);
