/**
 * V159 dataset typology and spec types.
 *
 * The JSON files next to this module are generated by
 * scripts/v159/import-dataset-spec-v159.mjs from the framework workbook and
 * the spec v2 assignment table; nothing here is hand-edited copy.
 */

/** Display type: the user question a screen answers (spec v2 §1). */
export type DisplayTypeV159 = "U0" | "U1" | "U2" | "U3" | "U4" | "U5" | "U6";
/** Data structure: the delivery shape the adapters normalise (spec v2 §2). */
export type StructureV159 = "S1" | "S2" | "S3" | "S4";

export const DISPLAY_TYPE_LABELS_V159: Record<DisplayTypeV159, string> = {
  U0: "상태 안내",
  U1: "국가 수준·추세",
  U2: "지역·입지",
  U3: "기술별 비교",
  U4: "시설·기관·인프라 위치",
  U5: "사업·재원",
  U6: "제도·규제·리스크",
};

/** Circled numerals the plan uses for the six types (⓪ for status). */
export const DISPLAY_TYPE_MARKS_V159: Record<DisplayTypeV159, string> = {
  U0: "⓪",
  U1: "①",
  U2: "②",
  U3: "③",
  U4: "④",
  U5: "⑤",
  U6: "⑥",
};

export const STRUCTURE_LABELS_V159: Record<StructureV159, string> = {
  S1: "국가×연도 관측값",
  S2: "지역×연도 관측값",
  S3: "위치 개체",
  S4: "비공간 개체",
};

export interface TypologyFlagsV159 {
  region: boolean;
  tech: boolean;
  geometry: boolean;
  categorical: boolean;
  scenario: boolean;
}

export interface TypologyRowV159 {
  elementId: string;
  displayType: DisplayTypeV159;
  displayTypeLabel: string;
  /** The type the spec v2 table assigned; differs where an excluded element became ⓪. */
  specDisplayType: DisplayTypeV159;
  structure: StructureV159;
  structureLabel: string;
  flags: TypologyFlagsV159;
  /** Spec v2 status column, e.g. "공개", "제외(사용자 0923)". */
  status: string;
  /** Spec v2 변형·비고 column, verbatim. */
  variant: string;
  /** Set for the six elements drawn by their own component. */
  dedicated: string | null;
  coverage: { VNM: string; BGD: string };
  specCaseCount: number;
}

export interface DatasetSpecRowV159 {
  elementId: string;
  platformName: string;
  platformNameEn: string;
  /** Source line shown above the name (split from platformName). */
  sourceLabel: string;
  /** Dataset name without the source prefix. */
  baseName: string;
  shortDefinition: string;
  /** shortDefinition without the leading "기관명(영문)이/가 " clause. */
  shortDefinitionCard: string;
  description: string;
  usage: string;
  definitionKo: string;
  sourceOrg: string;
  refLink: string;
  refApa: string;
  checkedAt: string;
  /** 금년도 최종 결정: 유지 · 제외 · 대체, or null when not decided. */
  decision: string | null;
  /** The workbook's stated reason for 제외/대체 (처리방향), verbatim; null when none. */
  decisionNote: string | null;
}

export interface UseCaseDataRefV159 {
  indicatorId: string | null;
  label: string;
  mapped: "exact" | "prefix" | "unmapped" | "label-only";
  /** Catalog indicators a prefix reference ("B-021_comp_sgdi_") stands for. */
  catalogIndicatorIds?: string[];
}

export interface UseCaseV159 {
  elementId: string;
  caseNo: number;
  purpose: string;
  purposeEn: string;
  logic: string;
  dataUsed: UseCaseDataRefV159[];
  storyline: string;
  users: string[];
  /** Source text; shown as the tooltip when cautionDisplay differs. */
  caution: string;
  /** Countries outside the platform registry replaced (see reports/v159). */
  cautionDisplay: string;
  verified: "verified" | "pending";
  verificationResult: string;
}

export interface DatasetCardSpecV159 {
  elementId: string;
  sourceLabel: string;
  baseName: string;
  shortDefinitionCard: string;
  displayType: DisplayTypeV159;
  /** Primary users across the element's cases, most frequent first. */
  users: string[];
}

/** Primary user groups the cases name (the finder's '주 사용자' filter). */
export const PRIMARY_USERS_V159 = ["공공기관", "기업", "금융기관", "연구자"] as const;
