export interface GlossaryEntryV74 {
  key: string;
  term: string;
  english: string;
  korean: string;
  aliases: string[];
  bullets: string[];
}

export const CLIMATE_GLOSSARY_V74: GlossaryEntryV74[] = [
  {
    key: "NDC",
    term: "NDC",
    english: "Nationally Determined Contribution",
    korean: "국가결정기여",
    aliases: ["NDC"],
    bullets: [
      "파리협정에 따라 국가가 제출하는 온실가스 감축·적응 목표",
      "목표연도·기준연도·조건부/무조건부 목표를 함께 확인",
      "최신 제출본과 이전 버전을 구분해 검토",
    ],
  },
  {
    key: "BTR",
    term: "BTR",
    english: "Biennial Transparency Report",
    korean: "격년투명성보고서",
    aliases: ["BTR"],
    bullets: [
      "파리협정 투명성체계에 따른 국가 보고서",
      "GHG 인벤토리·NDC 이행·지원 필요/수혜 정보를 포함",
      "제출본·보고기간·원문 근거를 함께 확인",
    ],
  },
  {
    key: "NAP",
    term: "NAP",
    english: "National Adaptation Plan",
    korean: "국가적응계획",
    aliases: ["NAP"],
    bullets: [
      "중장기 기후변화 적응계획",
      "취약부문·우선조치·투자수요·거버넌스를 확인",
      "문서 버전과 이행·M&E 체계를 함께 검토",
    ],
  },
  {
    key: "TNA",
    term: "TNA",
    english: "Technology Needs Assessment",
    korean: "기술수요평가",
    aliases: ["TNA"],
    bullets: [
      "개도국이 우선 기후기술 수요를 평가하는 절차·문서",
      "기술 우선순위·장벽·실행계획(TAP)을 확인",
      "기술협력 사업 수요 근거로 활용 가능",
    ],
  },
  {
    key: "LT-LEDS",
    term: "LT-LEDS",
    english: "Long-Term Low Emission Development Strategy",
    korean: "장기 저탄소 발전전략",
    aliases: ["LT-LEDS"],
    bullets: [
      "2050 전후 장기 감축·탈탄소 경로를 제시",
      "부문별 전환경로·에너지믹스·핵심기술을 확인",
      "NDC보다 장기 시계열의 전략 문서",
    ],
  },
  {
    key: "REDD+",
    term: "REDD+",
    english:
      "Reducing Emissions from Deforestation and Forest Degradation Plus",
    korean: "산림전용·산림황폐화 감축 플러스",
    aliases: ["REDD+", "REDD Plus"],
    bullets: [
      "산림전용·산림황폐화로 인한 배출 감축 체계",
      "산림탄소 보전·지속가능한 산림관리·탄소축적 증진 포함",
      "FREL·세이프가드·성과기반지급과 함께 검토",
    ],
  },
  {
    key: "FREL",
    term: "FREL",
    english: "Forest Reference Emission Level",
    korean: "산림 기준배출수준",
    aliases: ["FREL"],
    bullets: [
      "REDD+ 감축성과를 비교하는 기준선",
      "산림부문 기준배출량·기준기간을 설정",
      "제출연도·기준기간·기술평가 결과를 확인",
    ],
  },
  {
    key: "RBP",
    term: "RBP",
    english: "Results-Based Payment",
    korean: "결과기반지급",
    aliases: ["RBP"],
    bullets: [
      "검증된 REDD+ 감축성과에 연계된 지급",
      "성과량(tCO₂e)·지급액·지급기관을 함께 확인",
      "단순 사업비가 아니라 검증된 결과에 대한 지급",
    ],
  },
  {
    key: "SIS",
    term: "SIS",
    english: "Safeguard Information System",
    korean: "세이프가드 정보시스템",
    aliases: ["SIS"],
    bullets: [
      "REDD+ 세이프가드 이행 정보를 관리·보고",
      "환경·사회적 보호조치 이행상태를 확인",
      "최신 보고서와 운영 여부를 함께 검토",
    ],
  },
  {
    key: "ITMO",
    term: "ITMO",
    english: "Internationally Transferred Mitigation Outcomes",
    korean: "국제이전 감축성과",
    aliases: ["ITMO"],
    bullets: [
      "파리협정 제6.2조에서 국가 간 이전되는 감축성과",
      "승인·상응조정·등록·이전·보고 체계가 필요",
      "프로젝트 감축량과 국가 간 이전 가능성을 구분",
    ],
  },
  {
    key: "Article 6",
    term: "Article 6",
    english: "Paris Agreement Article 6",
    korean: "파리협정 제6조",
    aliases: ["Article 6", "제6조", "제6.2조", "제6.4조", "제6.8조"],
    bullets: [
      "국제감축·시장 및 비시장 협력을 다루는 조항",
      "제6.2조·제6.4조·제6.8조로 구분",
      "국가 승인·회계·보고·레지스트리 체계를 확인",
    ],
  },
  {
    key: "MRV",
    term: "MRV",
    english: "Measurement, Reporting and Verification",
    korean: "측정·보고·검증",
    aliases: ["MRV", "측정·보고·검증"],
    bullets: [
      "온실가스 감축성과를 측정·보고·검증하는 체계",
      "기준선·모니터링 변수·계측·QA/QC가 핵심",
      "방법론·검증기관·보고주기를 함께 확인",
    ],
  },
  {
    key: "GHG",
    term: "GHG",
    english: "Greenhouse Gas",
    korean: "온실가스",
    aliases: ["GHG"],
    bullets: [
      "CO₂·CH₄·N₂O·불소계가스 등 온실가스",
      "CO₂e로 환산해 합산하는 경우가 많음",
      "가스별·부문별 범위와 LULUCF 포함 여부 확인",
    ],
  },
  {
    key: "LULUCF",
    term: "LULUCF",
    english: "Land Use, Land-Use Change and Forestry",
    korean: "토지이용·토지이용변화·산림",
    aliases: ["LULUCF"],
    bullets: [
      "산림·농지·초지 등 토지이용 변화의 온실가스 배출·흡수 부문",
      "국가 총배출량에서 포함/제외 여부에 따라 값이 달라짐",
      "산림흡수원·토지피복 변화와 함께 검토",
    ],
  },
  {
    key: "GCF",
    term: "GCF",
    english: "Green Climate Fund",
    korean: "녹색기후기금",
    aliases: ["GCF", "녹색기후기금"],
    bullets: [
      "UNFCCC 재정메커니즘의 다자 기후기금",
      "감축·적응 프로젝트와 Readiness를 지원",
      "NDA·인증기구(AE)·승인재원·공동재원을 확인",
    ],
  },
  {
    key: "NDA",
    term: "NDA",
    english: "National Designated Authority",
    korean: "GCF 국가 지정기관",
    aliases: ["NDA"],
    bullets: [
      "GCF와 국가 간 공식 연락·조정 창구",
      "국가 우선순위 정합성·No-objection 절차 등에 관여",
      "기관명·소관부처·담당자·공식 역할 확인",
    ],
  },
  {
    key: "AE",
    term: "AE",
    english: "Accredited Entity",
    korean: "GCF 인증기구",
    aliases: ["AE"],
    bullets: [
      "GCF 사업을 제안·관리할 수 있도록 인증된 기관",
      "국제기구·개발은행·국가기관 등이 포함",
      "사업별 AE와 실행기관을 구분해 확인",
    ],
  },
  {
    key: "FCPF",
    term: "FCPF",
    english: "Forest Carbon Partnership Facility",
    korean: "산림탄소파트너십기금",
    aliases: ["FCPF"],
    bullets: [
      "REDD+ 준비·성과기반 산림탄소 프로그램 지원",
      "산림탄소 회계·MRV·정책 준비를 지원",
      "참여프로그램·성과지급 여부 확인",
    ],
  },
  {
    key: "BioCF",
    term: "BioCF",
    english: "BioCarbon Fund",
    korean: "바이오카본펀드",
    aliases: ["BioCF"],
    bullets: [
      "산림·토지이용 기반 감축과 농촌 저탄소 개발 지원",
      "세계은행 계열 탄소·기후재원 프로그램",
      "프로그램 참여·성과지급·대상지역을 확인",
    ],
  },
  {
    key: "GEF",
    term: "GEF",
    english: "Global Environment Facility",
    korean: "지구환경기금",
    aliases: ["GEF"],
    bullets: [
      "기후변화·생물다양성 등 글로벌 환경사업 지원",
      "다자 환경협약 이행을 지원하는 기금",
      "승인금액·수행기관·분야를 확인",
    ],
  },
  {
    key: "CIF",
    term: "CIF",
    english: "Climate Investment Funds",
    korean: "기후투자기금",
    aliases: ["CIF"],
    bullets: [
      "개발은행을 통해 청정기술·기후회복력 투자를 지원",
      "국가 투자계획과 프로젝트 포트폴리오로 구성",
      "공동재원·MDB·투자프로그램을 함께 확인",
    ],
  },
  {
    key: "CTCN",
    term: "CTCN",
    english: "Climate Technology Centre and Network",
    korean: "기후기술센터·네트워크",
    aliases: ["CTCN"],
    bullets: [
      "UNFCCC 기술메커니즘의 실행기구",
      "개도국 기술지원 요청(TA)을 지원",
      "NDE·지원단계·기술분야·결과를 확인",
    ],
  },
  {
    key: "NDE",
    term: "NDE",
    english: "National Designated Entity",
    korean: "CTCN 국가 지정기구",
    aliases: ["NDE"],
    bullets: [
      "CTCN과 국가 간 기술지원 공식 창구",
      "기술지원 요청 제출·조정 역할",
      "기관·담당자·연락처·요청 이력 확인",
    ],
  },
  {
    key: "DNA",
    term: "DNA",
    english: "Designated National Authority",
    korean: "파리협정/탄소시장 국가 지정기관",
    aliases: ["DNA"],
    bullets: [
      "국가별 탄소시장·메커니즘 승인 관련 공식 기관",
      "국가 제도에 따라 명칭·역할이 다를 수 있음",
      "승인절차·담당기관·전환상태 확인",
    ],
  },
  {
    key: "VCM",
    term: "VCM",
    english: "Voluntary Carbon Market",
    korean: "자발적 탄소시장",
    aliases: ["VCM"],
    bullets: [
      "법적 의무가 아닌 자발적 감축크레딧 시장",
      "VCS·Gold Standard 등 민간 표준 활용",
      "프로젝트·발행량·소각량·빈티지를 확인",
    ],
  },
  {
    key: "VCS",
    term: "VCS",
    english: "Verified Carbon Standard",
    korean: "검증 탄소표준",
    aliases: ["VCS"],
    bullets: [
      "Verra가 운영하는 자발적 탄소크레딧 표준",
      "프로젝트 등록·검증·크레딧 발행에 활용",
      "프로젝트 방법론·발행·소각 정보를 확인",
    ],
  },
  {
    key: "CBAM",
    term: "CBAM",
    english: "Carbon Border Adjustment Mechanism",
    korean: "탄소국경조정제도",
    aliases: ["CBAM", "탄소국경조정제도"],
    bullets: [
      "수입품 내재배출에 탄소비용을 반영하는 제도",
      "대상산업·품목·EU 수출노출도를 확인",
      "산업별 배출집약도와 무역구조를 함께 검토",
    ],
  },
  {
    key: "ETS",
    term: "ETS",
    english: "Emissions Trading System",
    korean: "배출권거래제",
    aliases: ["ETS", "배출권거래제"],
    bullets: [
      "총량 또는 기준을 설정하고 배출권을 거래하는 탄소가격제",
      "적용부문·할당방식·가격·MRV가 핵심",
      "탄소세와 구분해 검토",
    ],
  },
  {
    key: "LCOE",
    term: "LCOE",
    english: "Levelized Cost of Electricity",
    korean: "균등화 발전비용",
    aliases: ["LCOE", "균등화 발전비용"],
    bullets: [
      "발전소 수명기간의 총비용을 발전량으로 나눈 단위비용",
      "기술별 CAPEX·연료·O&M·할인율 등에 영향",
      "동일 가격연도·비용범위·가정을 맞춰 비교",
    ],
  },
  {
    key: "CAPEX",
    term: "CAPEX",
    english: "Capital Expenditure",
    korean: "자본적 지출",
    aliases: ["CAPEX", "단위 사업당 CAPEX"],
    bullets: [
      "설비 구축·건설에 필요한 초기 투자비",
      "기술별 단위는 USD/kW·USD/MW 등으로 달라질 수 있음",
      "EPC·토지·계통·개발비 포함범위를 반드시 확인",
    ],
  },
  {
    key: "MAC",
    term: "MAC",
    english: "Marginal Abatement Cost",
    korean: "한계저감비용",
    aliases: ["MAC"],
    bullets: [
      "추가 1 tCO₂e 감축에 필요한 비용",
      "음수이면 비용절감과 감축을 동시에 달성할 수 있음을 의미할 수 있음",
      "기술·기준선·감축잠재량 가정을 함께 확인",
    ],
  },
  {
    key: "TRL",
    term: "TRL",
    english: "Technology Readiness Level",
    korean: "기술준비수준",
    aliases: ["TRL", "기술준비수준"],
    bullets: [
      "기술의 연구·실증·상용화 성숙도를 단계로 평가",
      "일반적으로 TRL 1~9 체계를 사용",
      "기술별 실증·상용 프로젝트 근거와 함께 판정",
    ],
  },
  {
    key: "O&M",
    term: "O&M",
    english: "Operation and Maintenance",
    korean: "운영·유지보수",
    aliases: ["O&M", "운영·유지보수"],
    bullets: [
      "설비 운영과 예방·고장·예지 정비 활동",
      "인력·부품·서비스망·정비체계가 핵심",
      "현지 수행역량과 제조역량을 구분",
    ],
  },
  {
    key: "EPC",
    term: "EPC",
    english: "Engineering, Procurement and Construction",
    korean: "설계·조달·시공",
    aliases: ["EPC"],
    bullets: [
      "인프라 사업의 설계·조달·시공을 통합 수행하는 계약·역량",
      "해외 프로젝트 수행실적과 현지 조달역량이 중요",
      "O&M과 별도 수행단계로 구분",
    ],
  },
  {
    key: "EIA",
    term: "EIA",
    english: "Environmental Impact Assessment",
    korean: "환경영향평가",
    aliases: ["EIA", "환경영향평가"],
    bullets: [
      "사업 시행 전 환경영향을 조사·예측·평가하는 절차",
      "사업유형·규모·입지에 따라 필요범위가 달라짐",
      "토지·건축·사업허가와 병행·선후행 관계를 확인",
    ],
  },
  {
    key: "QA/QC",
    term: "QA/QC",
    english: "Quality Assurance / Quality Control",
    korean: "품질보증·품질관리",
    aliases: ["QA/QC"],
    bullets: [
      "데이터·측정·산정 결과의 품질을 관리하는 절차",
      "내부검토·재계산·오류관리·외부검토 등을 포함",
      "GHG 인벤토리·MRV 신뢰성에 중요",
    ],
  },
  {
    key: "SDG",
    term: "SDG",
    english: "Sustainable Development Goals",
    korean: "지속가능발전목표",
    aliases: ["SDG"],
    bullets: [
      "UN 2030 의제의 17개 지속가능발전목표",
      "기후·에너지·산업·빈곤·생태계 등과 연계",
      "NDC 조치와의 연계는 근거 논리를 함께 확인",
    ],
  },
  {
    key: "SSP",
    term: "SSP",
    english: "Shared Socioeconomic Pathways",
    korean: "공통사회경제경로",
    aliases: ["SSP"],
    bullets: [
      "기후변화 시나리오에서 사용하는 사회경제 발전경로",
      "SSP별 인구·GDP·배출·기후전망이 달라질 수 있음",
      "동일 SSP와 전망시점을 맞춰 비교",
    ],
  },
  {
    key: "CMIP6",
    term: "CMIP6",
    english: "Coupled Model Intercomparison Project Phase 6",
    korean: "제6차 결합모델 상호비교사업",
    aliases: ["CMIP6"],
    bullets: [
      "다수 기후모델의 과거·미래 기후전망을 비교하는 국제 프로젝트",
      "기온·강수·풍속 등 기후변수 자료에 활용",
      "모델·SSP·기간·공간해상도를 함께 확인",
    ],
  },
  {
    key: "GHI",
    term: "GHI",
    english: "Global Horizontal Irradiance",
    korean: "수평면 전일사량",
    aliases: ["GHI"],
    bullets: [
      "수평면에 도달하는 총 태양복사량",
      "태양광 발전 잠재량 평가의 핵심 자원지표",
      "단위·기간·공간해상도 확인 필요",
    ],
  },
  {
    key: "DNI",
    term: "DNI",
    english: "Direct Normal Irradiance",
    korean: "법선면 직달일사량",
    aliases: ["DNI"],
    bullets: [
      "태양광 중 직접 도달하는 복사량",
      "집광형 태양열·일부 태양광 자원평가에 중요",
      "GHI와 다른 물리량이므로 혼합하지 않음",
    ],
  },
  {
    key: "PVOUT",
    term: "PVOUT",
    english: "Photovoltaic Power Output",
    korean: "태양광 발전 잠재출력",
    aliases: ["PVOUT"],
    bullets: [
      "표준 PV 시스템이 생산할 수 있는 예상 발전량 지표",
      "일사량·온도·시스템 손실 등을 반영",
      "kWh/kWp 등 단위와 가정 확인",
    ],
  },
  {
    key: "CDD",
    term: "CDD",
    english: "Consecutive Dry Days",
    korean: "연속 건조일수",
    aliases: ["CDD"],
    bullets: [
      "강수가 기준 이하인 날이 연속되는 최대 기간",
      "가뭄·건조 위험을 나타내는 기후극한지수",
      "기준 강수량·기간을 확인",
    ],
  },
  {
    key: "SPEI12",
    term: "SPEI12",
    english: "Standardized Precipitation Evapotranspiration Index (12-month)",
    korean: "12개월 표준강수증발산지수",
    aliases: ["SPEI12"],
    bullets: [
      "강수와 잠재증발산을 함께 반영한 가뭄지수",
      "12개월 누적 규모로 장기 수문·생태 가뭄을 파악",
      "음수일수록 건조한 조건을 의미",
    ],
  },
  {
    key: "TX35",
    term: "TX35",
    english: "Days with Tmax ≥ 35°C",
    korean: "일최고기온 35°C 이상 일수",
    aliases: ["TX35"],
    bullets: [
      "폭염 노출을 나타내는 기후극한지수",
      "일최고기온이 35°C 이상인 날의 수",
      "TX40과 임계온도가 다름",
    ],
  },
  {
    key: "TX40",
    term: "TX40",
    english: "Days with Tmax ≥ 40°C",
    korean: "일최고기온 40°C 이상 일수",
    aliases: ["TX40"],
    bullets: [
      "매우 강한 고온 노출일수",
      "TX35보다 높은 임계값을 사용",
      "기간·시나리오별 변화 확인",
    ],
  },
  {
    key: "TR20",
    term: "TR20",
    english: "Tropical Nights with Tmin ≥ 20°C",
    korean: "최저기온 20°C 이상 열대야 일수",
    aliases: ["TR20"],
    bullets: [
      "야간 최저기온이 20°C 이상인 날의 수",
      "야간 열스트레스·냉방수요와 관련",
      "TR25와 임계온도가 다름",
    ],
  },
  {
    key: "TR25",
    term: "TR25",
    english: "Tropical Nights with Tmin ≥ 25°C",
    korean: "최저기온 25°C 이상 열대야 일수",
    aliases: ["TR25"],
    bullets: [
      "강한 야간 고온 노출을 나타내는 지수",
      "TR20보다 엄격한 임계값 사용",
      "건강·냉방부하 평가에 활용",
    ],
  },
  {
    key: "HI35",
    term: "HI35",
    english: "Heat Index ≥ 35°C",
    korean: "고온체감지수 35°C 이상 일수",
    aliases: ["HI35"],
    bullets: [
      "기온과 습도를 결합한 체감열 스트레스 지표",
      "단순 기온 임계지수(TX35)와 다름",
      "건강·노동·냉방 적응 검토에 활용",
    ],
  },
  {
    key: "RX1day",
    term: "RX1day",
    english: "Maximum 1-day Precipitation",
    korean: "연 최대 1일 강수량",
    aliases: ["RX1day"],
    bullets: [
      "일 단위 극한강수의 최대값",
      "홍수·배수 인프라 위험평가에 활용",
      "RX5day와 누적기간이 다름",
    ],
  },
  {
    key: "RX5day",
    term: "RX5day",
    english: "Maximum Consecutive 5-day Precipitation",
    korean: "연 최대 연속 5일 강수량",
    aliases: ["RX5day"],
    bullets: [
      "연속 5일 누적 극한강수 최대값",
      "장기간 집중호우·유역 홍수 위험과 관련",
      "기간·모델·시나리오 확인",
    ],
  },
  {
    key: "R20mm",
    term: "R20mm",
    english: "Very Heavy Precipitation Days ≥20mm",
    korean: "20mm 이상 강수일수",
    aliases: ["R20mm", "R20"],
    bullets: [
      "일강수량 20mm 이상인 날의 수",
      "강우 빈도형 극한지수",
      "국가·기관 정의에 따라 명칭이 달라질 수 있음",
    ],
  },
  {
    key: "R50mm",
    term: "R50mm",
    english: "Heavy Precipitation Days ≥50mm",
    korean: "50mm 이상 강수일수",
    aliases: ["R50mm", "R50"],
    bullets: [
      "일강수량 50mm 이상인 날의 수",
      "더 강한 호우 빈도를 나타냄",
      "기준기관 정의 확인 필요",
    ],
  },
  {
    key: "CWD",
    term: "CWD",
    english: "Consecutive Wet Days",
    korean: "연속 습윤일수",
    aliases: ["CWD"],
    bullets: [
      "강수가 기준 이상인 날이 연속되는 최대 기간",
      "장기 습윤·홍수·토양수분 조건과 관련",
      "CDD와 반대 성격의 지수",
    ],
  },
  {
    key: "SAIDI",
    term: "SAIDI",
    english: "System Average Interruption Duration Index",
    korean: "고객 평균 정전시간 지수",
    aliases: ["SAIDI"],
    bullets: [
      "고객 1명당 평균 정전 지속시간",
      "배전 신뢰도 지표",
      "SAIFI와 함께 빈도·시간을 구분해 해석",
    ],
  },
  {
    key: "SAIFI",
    term: "SAIFI",
    english: "System Average Interruption Frequency Index",
    korean: "고객 평균 정전횟수 지수",
    aliases: ["SAIFI"],
    bullets: [
      "고객 1명당 평균 정전 발생횟수",
      "배전 신뢰도 지표",
      "SAIDI와 함께 사용",
    ],
  },
  {
    key: "LPI",
    term: "LPI",
    english: "Logistics Performance Index",
    korean: "물류성과지수",
    aliases: ["LPI"],
    bullets: [
      "국가 물류·통관·인프라·배송역량을 평가하는 지수",
      "사업 기자재 조달·수출입 여건 판단에 참고",
      "연도·방법론 변경 여부 확인",
    ],
  },
  {
    key: "LSCI",
    term: "LSCI",
    english: "Liner Shipping Connectivity Index",
    korean: "정기선 해운연결성지수",
    aliases: ["LSCI"],
    bullets: [
      "국가의 국제 정기선 해운 연결성을 나타내는 지수",
      "항만·선박·노선 연결성에 기반",
      "수출입 물류 접근성 판단에 활용",
    ],
  },
  {
    key: "ND-GAIN",
    term: "ND-GAIN",
    english: "Notre Dame Global Adaptation Initiative Index",
    korean: "ND-GAIN 기후취약성·준비도 지수",
    aliases: ["ND-GAIN"],
    bullets: [
      "국가의 기후취약성과 적응 준비도를 종합평가",
      "취약성·준비도 하위요소로 구성",
      "특정 사업의 기술수요를 직접 의미하지 않음",
    ],
  },
  {
    key: "GII",
    term: "GII",
    english: "Global Innovation Index",
    korean: "글로벌 혁신지수",
    aliases: ["GII"],
    bullets: [
      "국가 혁신 투입·산출 역량을 종합평가",
      "특허·R&D·인력·제도 등 다양한 요소 반영",
      "기후기술 특정 역량과 구분해 해석",
    ],
  },
  {
    key: "STEM",
    term: "STEM",
    english: "Science, Technology, Engineering and Mathematics",
    korean: "과학·기술·공학·수학",
    aliases: ["STEM"],
    bullets: [
      "기술인력·연구인력 기반을 나타내는 교육·인력 분야",
      "졸업자 수와 연구자 수는 서로 다른 지표",
      "기후기술 전문인력과 직접 동일시하지 않음",
    ],
  },
  {
    key: "R&D",
    term: "R&D",
    english: "Research and Development",
    korean: "연구개발",
    aliases: ["R&D", "연구개발"],
    bullets: [
      "새로운 지식·기술·제품을 개발하는 연구개발 활동",
      "지출액·GDP 대비 비중·인력·특허와 함께 평가",
      "기술사업화·TRL과 구분해 해석",
    ],
  },
  {
    key: "ODA",
    term: "ODA",
    english: "Official Development Assistance",
    korean: "공적개발원조",
    aliases: ["ODA", "공적개발원조"],
    bullets: [
      "개발도상국의 경제·사회발전을 지원하는 공적재원",
      "무상·유상원조와 기술협력 등 다양한 형태",
      "사업기간·시행기관·DAC 분야·재원조건을 확인",
    ],
  },
  {
    key: "EDCF",
    term: "EDCF",
    english: "Economic Development Cooperation Fund",
    korean: "대외경제협력기금",
    aliases: ["EDCF", "대외경제협력기금"],
    bullets: [
      "한국의 유상원조 기금",
      "개도국 인프라·경제개발 사업에 장기 저리금융 제공",
      "승인액·금리·상환기간·거치기간을 확인",
    ],
  },
  {
    key: "MDB",
    term: "MDB",
    english: "Multilateral Development Bank",
    korean: "다자개발은행",
    aliases: ["MDB"],
    bullets: [
      "여러 국가가 출자한 국제개발금융기관",
      "세계은행·ADB 등과 프로젝트·정책금융 수행",
      "대출·보증·투자·기술지원 조건 확인",
    ],
  },
  {
    key: "DFI",
    term: "DFI",
    english: "Development Finance Institution",
    korean: "개발금융기관",
    aliases: ["DFI"],
    bullets: [
      "개발성과와 민간투자를 촉진하는 공공·준공공 금융기관",
      "대출·지분·보증 등 다양한 금융수단 활용",
      "MDB와 기관범위가 일부 겹칠 수 있음",
    ],
  },
  {
    key: "PPI",
    term: "PPI",
    english: "Private Participation in Infrastructure",
    korean: "민간 인프라 참여",
    aliases: ["PPI"],
    bullets: [
      "인프라 사업에 민간이 투자·운영하는 프로젝트 데이터 범주",
      "Greenfield·Concession 등 사업유형 포함",
      "투자액·계약기간·스폰서·상태 확인",
    ],
  },
  {
    key: "MIGA",
    term: "MIGA",
    english: "Multilateral Investment Guarantee Agency",
    korean: "다자간투자보증기구",
    aliases: ["MIGA"],
    bullets: [
      "세계은행그룹의 정치적 리스크 보증기관",
      "수용·송금제한·계약위반·전쟁/내란 등 위험 보증",
      "보증금액·기간·투자자·프로젝트 확인",
    ],
  },
  {
    key: "PCP",
    term: "PCP",
    english: "Project Concept Paper",
    korean: "사업개념서",
    aliases: ["PCP"],
    bullets: [
      "개발협력 사업의 초기 개념·기획 문서",
      "기관별 절차에서 제안·검토 단계에 활용",
      "사업목표·대상국·예산·수행방식을 확인",
    ],
  },
  {
    key: "RFP",
    term: "RFP",
    english: "Request for Proposal",
    korean: "제안요청서",
    aliases: ["RFP"],
    bullets: [
      "발주기관이 수행기관의 기술·가격 제안을 요청하는 문서",
      "제안범위·자격·평가기준·마감일을 포함",
      "PCP와 발주·입찰 단계가 다름",
    ],
  },
  {
    key: "DAC",
    term: "DAC",
    english: "Development Assistance Committee",
    korean: "OECD 개발원조위원회",
    aliases: ["DAC"],
    bullets: [
      "ODA 통계·분류 기준을 관리",
      "DAC 목적코드로 원조 분야를 분류",
      "프로젝트 분야 비교 시 코드 정의 확인",
    ],
  },
  {
    key: "Rio Marker",
    term: "Rio Marker",
    english: "OECD Rio Marker",
    korean: "리우마커",
    aliases: ["Rio Marker"],
    bullets: [
      "ODA 활동의 기후·환경 목적성을 태깅하는 지표",
      "주목적·부목적·비해당 등으로 구분",
      "실제 감축량이나 성과지표와는 다름",
    ],
  },
  {
    key: "FIT",
    term: "FIT",
    english: "Feed-in Tariff",
    korean: "발전차액지원제도",
    aliases: ["FIT"],
    bullets: [
      "재생에너지 전력을 정해진 가격으로 구매하는 지원제도",
      "기술별 가격·기간·용량조건을 확인",
      "FIP·RPS·경쟁입찰과 제도방식이 다름",
    ],
  },
  {
    key: "FIP",
    term: "FIP",
    english: "Feed-in Premium",
    korean: "발전 프리미엄 제도",
    aliases: ["FIP"],
    bullets: [
      "시장가격에 프리미엄을 추가 지급하는 재생에너지 지원제도",
      "고정가격 FIT와 구조가 다름",
      "프리미엄 산정·기간·대상기술 확인",
    ],
  },
  {
    key: "RPS",
    term: "RPS",
    english: "Renewable Portfolio Standard",
    korean: "신재생에너지 공급의무제",
    aliases: ["RPS"],
    bullets: [
      "발전사업자 등에 일정 비율의 재생에너지 공급을 의무화",
      "의무비율·인증서·대상사업자를 확인",
      "FIT/FIP와 정책수단이 다름",
    ],
  },
  {
    key: "AUM",
    term: "AUM",
    english: "Assets Under Management",
    korean: "운용자산규모",
    aliases: ["AUM"],
    bullets: [
      "투자기관이 운용하는 총 자산규모",
      "기후기술 투자실적과 직접 동일하지 않음",
      "투자전략·티켓규모·지역범위와 함께 확인",
    ],
  },
  {
    key: "UNFCCC",
    term: "UNFCCC",
    english: "United Nations Framework Convention on Climate Change",
    korean: "유엔기후변화협약",
    aliases: ["UNFCCC"],
    bullets: [
      "국제 기후변화 협약과 협상체계",
      "NDC·BTR·Article 6·기후기금 등 주요 제도 기반",
      "공식 제출문서 확인 시 핵심 원천",
    ],
  },
  {
    key: "IEA",
    term: "IEA",
    english: "International Energy Agency",
    korean: "국제에너지기구",
    aliases: ["IEA"],
    bullets: [
      "에너지 통계·전망·정책분석 제공",
      "에너지수요·전원구성·기술전망에 활용",
      "시나리오·기준연도·가정 확인 필요",
    ],
  },
  {
    key: "IRENA",
    term: "IRENA",
    english: "International Renewable Energy Agency",
    korean: "국제재생에너지기구",
    aliases: ["IRENA"],
    bullets: [
      "재생에너지 비용·용량·정책·자원 자료 제공",
      "LCOE·CAPEX·재생에너지 통계에 활용",
      "자료 정의·지역범위 확인",
    ],
  },
  {
    key: "WIPO",
    term: "WIPO",
    english: "World Intellectual Property Organization",
    korean: "세계지식재산기구",
    aliases: ["WIPO"],
    bullets: [
      "특허·지식재산 국제통계와 제도 지원",
      "기술별 특허·출원인·국제출원 분석에 활용",
      "특허건수와 기술사업성을 직접 동일시하지 않음",
    ],
  },
  {
    key: "UNESCO",
    term: "UNESCO",
    english: "United Nations Educational, Scientific and Cultural Organization",
    korean: "유네스코",
    aliases: ["UNESCO"],
    bullets: [
      "교육·과학·문화 분야 국제기구",
      "연구자·R&D·교육통계에 활용",
      "UIS 등 세부 통계기관 자료 확인",
    ],
  },
  {
    key: "ADB",
    term: "ADB",
    english: "Asian Development Bank",
    korean: "아시아개발은행",
    aliases: ["ADB"],
    bullets: [
      "아시아·태평양 개발금융기관",
      "인프라·기후·에너지 사업에 대출·보조금·기술지원 제공",
      "프로젝트·재원조건·수행기관 확인",
    ],
  },
  {
    key: "IFC",
    term: "IFC",
    english: "International Finance Corporation",
    korean: "국제금융공사",
    aliases: ["IFC"],
    bullets: [
      "세계은행그룹의 민간부문 투자기관",
      "대출·지분·자문 등을 통해 민간 프로젝트 지원",
      "공공개발은행 사업과 구분해 확인",
    ],
  },
  {
    key: "CO₂e",
    term: "CO₂e",
    english: "Carbon Dioxide Equivalent",
    korean: "이산화탄소환산량",
    aliases: ["CO₂e"],
    bullets: [
      "서로 다른 온실가스를 지구온난화 영향 기준으로 CO₂ 양으로 환산",
      "tCO₂e·MtCO₂e 단위로 많이 사용",
      "GWP 기준과 포함가스를 확인",
    ],
  },
  {
    key: "tCO₂e",
    term: "tCO₂e",
    english: "tonnes of CO₂ equivalent",
    korean: "톤 이산화탄소환산량",
    aliases: ["tCO₂e"],
    bullets: [
      "온실가스 감축·배출량의 기본 단위",
      "1 tCO₂e = CO₂ 1톤과 같은 온난화영향으로 환산",
      "기준선·기간·가스범위 확인",
    ],
  },
  {
    key: "MtCO₂e",
    term: "MtCO₂e",
    english: "million tonnes of CO₂ equivalent",
    korean: "백만 톤 이산화탄소환산량",
    aliases: ["MtCO₂e"],
    bullets: [
      "1 MtCO₂e = 1,000,000 tCO₂e",
      "국가·부문 단위 배출량에 주로 사용",
      "LULUCF 포함 여부와 기준연도 확인",
    ],
  },
];

export const GLOSSARY_ALIASES_V74 = CLIMATE_GLOSSARY_V74.flatMap((entry) =>
  entry.aliases.map((alias) => ({ alias, entry }))
).sort((a, b) => b.alias.length - a.alias.length);
