"""V165-2: elements outside the 2026 collection scope, the same rule for every country.

``config/data-publication/collection-scope-v165.json`` lists the elements the
framework marks as not collected in 2026 (``db_framework`` column
``2026_수집여부`` = N). On 2026-10-05 the user decided that what the Bangladesh
delivery marks "2026 수집 대상 아님" holds for Viet Nam too.

The rule:

- an element in the list whose delivery holds no populated row (status
  ``not-collected``, ``schema-only`` or ``data-entry-planned``) is listed as
  not provided (``not-provided``) and so leaves every public list, search and
  item count, as the Bangladesh delivery's absent elements already do;
- an element in the list with populated rows stays as published: the scope
  says what is collected this year, not that delivered data stops existing;
- an element excluded by decision stays excluded.

Nothing is removed from the files: values, rows, packs and downloads are not
touched. Only the status fields of the catalog, the framework coverage and the
bundle index change, with the package reason saying why, and the manifest's
status counts follow.

The ETLs (``build_public_v2`` and the Bangladesh ``build_country_v2``) apply
``apply_collection_scope_v165`` before writing; run as a script it applies the
same rule to the data already published, without the raw delivery:

    python -m tools.etl.collection_scope_v165 [--check]

Afterwards the card summaries, the dataset directory and the asset integrity
file are regenerated by their own scripts.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any, Iterable, Mapping

ROOT = pathlib.Path(__file__).resolve().parents[2]
SCOPE_PATH = "config/data-publication/collection-scope-v165.json"
COUNTRIES = {"VNM": ROOT / "public/data/vietnam/v2", "BGD": ROOT / "public/data/bgd/v2"}

# Statuses that mean "no populated row in the delivery".
NO_DATA_STATUSES_V165 = frozenset({"not-collected", "schema-only", "data-entry-planned"})


def load_collection_scope_v165(repo: pathlib.Path = ROOT) -> dict[str, Any]:
    """The decision file, checked: a declared count that matches its list, no repeats."""
    doc = json.loads((repo / SCOPE_PATH).read_text(encoding="utf-8"))
    ids = [str(value) for value in doc.get("elementIds", [])]
    if len(ids) != len(set(ids)):
        raise ValueError("collection scope lists an element twice")
    if int(doc.get("elementCount", -1)) != len(ids):
        raise ValueError(f"collection scope count {doc.get('elementCount')} does not match its list ({len(ids)})")
    if not str(doc.get("packageReason") or "").strip():
        raise ValueError("collection scope without a package reason")
    return {"ids": frozenset(ids), "packageReason": str(doc["packageReason"]).strip()}


def _out_of_scope_without_data(row: Mapping[str, Any], ids: frozenset[str]) -> bool:
    return str(row.get("elementId")) in ids and str(row.get("publicStatus")) in NO_DATA_STATUSES_V165


def apply_to_catalog_v165(rows: Iterable[dict[str, Any]], scope: Mapping[str, Any]) -> list[str]:
    """Mark the catalog rows the rule reaches; returns their element ids."""
    changed: list[str] = []
    for row in rows:
        if not _out_of_scope_without_data(row, scope["ids"]):
            continue
        has_workbook = bool((row.get("sourceWorkbook") or {}).get("exists")) or row.get("packageStatus") == "provided"
        row["publicStatus"] = "not-provided"
        row["dataPresenceStatus"] = "not-provided"
        row["emptyReason"] = "not-provided"
        row["downloadAllowed"] = False
        row["collectionPlanned"] = False
        if not has_workbook:
            row["packageStatus"] = "not-provided"
        # The reason says what the delivery held, then the scope.
        held = "입력 양식만 있고 값이 든 원자료 행 없음" if has_workbook else "원자료 없음"
        row["packageReason"] = f"{held} · {scope['packageReason']}"
        changed.append(str(row["elementId"]))
    return changed


def apply_to_coverage_v165(
    rows: Iterable[dict[str, Any]], scope: Mapping[str, Any], catalog_rows: Iterable[Mapping[str, Any]]
) -> list[str]:
    """The coverage follows the catalog: only the elements the catalog now lists as not provided.

    An element excluded by decision keeps its measured status here, as before.
    """
    marked = {str(row.get("elementId")) for row in catalog_rows if row.get("publicStatus") == "not-provided"}
    changed: list[str] = []
    for row in rows:
        if str(row.get("elementId")) not in marked or not _out_of_scope_without_data(row, scope["ids"]):
            continue
        row["publicStatus"] = "not-provided"
        row["dataPresenceStatus"] = "not-provided"
        row["emptyReason"] = "not-provided"
        changed.append(str(row["elementId"]))
    return changed


def apply_to_bundle_index_v165(index: dict[str, Any], catalog_rows: Iterable[Mapping[str, Any]]) -> list[str]:
    """The bundle index repeats each element's statuses; it follows the catalog."""
    changed: list[str] = []
    elements = index.get("elements") or {}
    for row in catalog_rows:
        entry = elements.get(str(row.get("elementId")))
        if not entry or row.get("publicStatus") != "not-provided" or entry.get("publicStatus") == "not-provided":
            continue
        entry["publicStatus"] = "not-provided"
        entry["packageStatus"] = row.get("packageStatus", entry.get("packageStatus"))
        changed.append(str(row["elementId"]))
    return changed


def recount_manifest_v165(manifest: dict[str, Any], catalog_rows: Iterable[Mapping[str, Any]]) -> list[str]:
    """The manifest's status counts follow the catalog (every status it already
    lists keeps its key, at 0 when none is left); returns the statuses whose
    count changed."""
    counts = manifest.get("publicStatusCounts")
    if not isinstance(counts, dict):
        return []
    tally: dict[str, int] = {}
    for row in catalog_rows:
        status = str(row.get("publicStatus"))
        tally[status] = tally.get(status, 0) + 1
    updated = {key: tally.get(key, 0) for key in sorted(set(counts) | set(tally))}
    changed = [key for key in updated if counts.get(key) != updated[key]]
    if changed:
        manifest["publicStatusCounts"] = updated
    return changed


def apply_collection_scope_v165(
    catalog: list[dict[str, Any]],
    coverage: list[dict[str, Any]] | None = None,
    *,
    repo: pathlib.Path = ROOT,
) -> list[str]:
    """For the ETLs: apply the rule to the rows about to be written."""
    scope = load_collection_scope_v165(repo)
    changed = apply_to_catalog_v165(catalog, scope)
    if coverage is not None:
        apply_to_coverage_v165(coverage, scope, catalog)
    return changed


def _json_bytes(value: Any) -> bytes:
    # The ETLs' pretty form (build_public_v2._json_bytes(pretty=True)).
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode("utf-8")


def _apply_country(root: pathlib.Path, scope: Mapping[str, Any], write: bool) -> dict[str, list[str]]:
    paths = {
        "catalog": root / "catalog.json",
        "coverage": root / "framework-coverage.json",
        "bundle": root / "packs/bundle-index-v124.json",
        "manifest": root / "manifest.json",
    }
    docs = {name: json.loads(path.read_text(encoding="utf-8")) for name, path in paths.items() if path.is_file()}
    result = {
        "catalog": apply_to_catalog_v165(docs["catalog"]["elements"], scope),
        "coverage": apply_to_coverage_v165(docs["coverage"]["elements"], scope, docs["catalog"]["elements"]) if "coverage" in docs else [],
    }
    result["bundle"] = apply_to_bundle_index_v165(docs["bundle"], docs["catalog"]["elements"]) if "bundle" in docs else []
    result["manifest"] = recount_manifest_v165(docs["manifest"], docs["catalog"]["elements"]) if "manifest" in docs else []
    if write:
        for name, path in paths.items():
            if name in docs and result[name]:
                path.write_bytes(_json_bytes(docs[name]))
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report what would change; exit 1 if anything would")
    args = parser.parse_args(argv)
    scope = load_collection_scope_v165()
    pending = False
    for iso3, root in COUNTRIES.items():
        result = _apply_country(root, scope, write=not args.check)
        print(json.dumps({"country": iso3, **result}, ensure_ascii=False))
        pending = pending or any(result.values())
    return 1 if args.check and pending else 0


if __name__ == "__main__":
    sys.exit(main())
