"""V165-2: apply the exclusion decisions to the data already published.

The ETLs (``build_public_v2`` for Viet Nam, ``countries/bgd/build_country_v2``
for Bangladesh) read the exclusion decisions - the decision common to every
country (``config/data-publication/common-exclusions-v158.json``) plus a
country's own - and mark each decided element while they build. On 2026-10-05
the user decided that the five elements the framework does not collect in
2026 (``db_framework`` column ``2026_수집여부`` = N: C-023, D-001, D-002, D-004,
E-013) are not offered in any country, whatever a delivery holds, so every
country offers the same 141 of the 152 elements. The decision was added to the
common file; the next ETL run picks it up as it is.

This script applies the same decisions to the published files without the raw
delivery, exactly as the ETL marks an excluded element:

- catalog: ``publicStatus`` = ``excluded``, ``downloadAllowed`` = false, and an
  ``exclusion`` record (reason, basis, date, public notice, and the status and
  presence that were measured); every other field - counts, files, download
  assets - stays as measured: "an excluded element keeps its files but is not
  offered";
- bundle index: the element's ``publicStatus`` follows the catalog;
- manifest: the status counts and the downloadable-element count follow the
  catalog (Viet Nam's ETL lists every allowed status, Bangladesh's the ones
  present).

The framework coverage keeps the measured status (as for the earlier
exclusions); values, records, packs and downloads are not touched. The card
summaries, semantic contracts, dataset directory and asset integrity are
regenerated by their own scripts afterwards.

Usage: python -m tools.etl.reapply_exclusions_v165 [--check]
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any, Mapping

from .build_public_v2 import _country_config, load_exclusion_decisions

ROOT = pathlib.Path(__file__).resolve().parents[2]
COUNTRIES = {"VNM": ROOT / "public/data/vietnam/v2", "BGD": ROOT / "public/data/bgd/v2"}
# Viet Nam's manifest lists every status its ETL allows (at 0 when none);
# Bangladesh's lists the statuses present.
ALL_STATUS_KEYS = {"VNM": True, "BGD": False}


def _json_bytes(value: Any) -> bytes:
    # The ETLs' pretty form (build_public_v2._json_bytes(pretty=True)).
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode("utf-8")


def apply_to_catalog(rows: list[dict[str, Any]], decisions: Mapping[str, Mapping[str, Any]]) -> list[str]:
    changed: list[str] = []
    for row in rows:
        decision = decisions.get(str(row.get("elementId")))
        if not decision or row.get("publicStatus") == "excluded":
            continue
        measured_status = row.get("publicStatus")
        measured_presence = row.get("dataPresenceStatus")
        row["publicStatus"] = "excluded"
        row["downloadAllowed"] = False
        row["exclusion"] = {
            "reason": str(decision.get("reason") or ""),
            "basis": str(decision.get("basis") or ""),
            "decidedAt": str(decision.get("decidedAt") or ""),
            "publicNotice": str(decision.get("publicNotice") or ""),
            "measuredStatus": measured_status,
            "measuredPresence": measured_presence,
        }
        changed.append(str(row["elementId"]))
    return changed


def apply_to_bundle_index(index: dict[str, Any], rows: list[Mapping[str, Any]]) -> list[str]:
    changed: list[str] = []
    elements = index.get("elements") or {}
    for row in rows:
        entry = elements.get(str(row.get("elementId")))
        if entry and row.get("publicStatus") == "excluded" and entry.get("publicStatus") != "excluded":
            entry["publicStatus"] = "excluded"
            changed.append(str(row["elementId"]))
    return changed


def recount_manifest(manifest: dict[str, Any], rows: list[Mapping[str, Any]], all_keys: bool) -> list[str]:
    changed: list[str] = []
    tally: dict[str, int] = {}
    for row in rows:
        status = str(row.get("publicStatus"))
        tally[status] = tally.get(status, 0) + 1
    counts = manifest.get("publicStatusCounts") or {}
    keys = sorted(set(counts) | set(tally)) if all_keys else sorted(tally)
    updated = {key: tally.get(key, 0) for key in keys}
    if updated != counts:
        manifest["publicStatusCounts"] = updated
        changed.append("publicStatusCounts")
    downloadable = sum(bool(row.get("downloadAssets")) and row.get("publicStatus") != "excluded" for row in rows)
    if manifest.get("downloadableElementCount") != downloadable:
        manifest["downloadableElementCount"] = downloadable
        changed.append("downloadableElementCount")
    return changed


def _apply_country(iso3: str, root: pathlib.Path, write: bool) -> dict[str, list[str]]:
    decisions = load_exclusion_decisions(ROOT, _country_config(ROOT, iso3))
    paths = {
        "catalog": root / "catalog.json",
        "bundle": root / "packs/bundle-index-v124.json",
        "manifest": root / "manifest.json",
    }
    docs = {name: json.loads(path.read_text(encoding="utf-8")) for name, path in paths.items()}
    rows = docs["catalog"]["elements"]
    result = {
        "catalog": apply_to_catalog(rows, decisions),
        "bundle": apply_to_bundle_index(docs["bundle"], rows),
        "manifest": recount_manifest(docs["manifest"], rows, ALL_STATUS_KEYS[iso3]),
    }
    if write:
        for name, path in paths.items():
            if result[name]:
                path.write_bytes(_json_bytes(docs[name]))
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report what would change; exit 1 if anything would")
    args = parser.parse_args(argv)
    pending = False
    for iso3, root in COUNTRIES.items():
        result = _apply_country(iso3, root, write=not args.check)
        print(json.dumps({"country": iso3, **result}, ensure_ascii=False))
        pending = pending or any(result.values())
    return 1 if args.check and pending else 0


if __name__ == "__main__":
    sys.exit(main())
