"""V164: take the delivery's licence review out of the shipped download ZIPs.

The V163-DL cleaning (public_text_v163) left the licence review the delivery
wrote after a licence name or in a caveat ("[라이선스 X] … 표출 '불가'로
판정한다.", "라이선스 판정: … '가능'."). The ETL now applies
``clean_licence_review_v164`` on every run; this script applies only that rule
to the ZIPs already published, without the raw delivery:

- JSON members: the licence, attribution and caveat text fields are cleaned;
  the document is written back in the ETL's canonical form (byte-identical
  when nothing changed).
- CSV members: only the ``license_code`` column is cleaned; every other cell is
  written back as read (byte-identical round trip checked first).
- Values, units, years, keys and coordinates are never touched: the script
  checks that the cleaned JSON differs from the original only in those text
  fields and that every CSV row keeps its other columns.
- The catalog's member and ZIP digests are updated; the dataset directory and
  the asset integrity file are regenerated by their own scripts afterwards.

Usage: python -m tools.etl.reclean_download_licence_v164 [--check]
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import pathlib
import sys
import zipfile
from typing import Any

from .download_zip_v158 import zip_bytes
from .normalization import canonical_json
from .public_text_v163 import LICENCE_TEXT_KEYS_V164, clean_licence_review_v164

ROOT = pathlib.Path(__file__).resolve().parents[2]
COUNTRIES = {"VNM": ROOT / "public/data/vietnam/v2", "BGD": ROOT / "public/data/bgd/v2"}


def _clean_tree(node: Any, key: str, changes: list[tuple[str, str]]) -> Any:
    if isinstance(node, dict):
        return {k: _clean_tree(v, k, changes) for k, v in node.items()}
    if isinstance(node, list):
        cleaned = [_clean_tree(item, key, changes) for item in node]
        if key in LICENCE_TEXT_KEYS_V164 and all(isinstance(item, str) for item in cleaned):
            deduped: list[Any] = []
            for item in cleaned:
                if item and item not in deduped:
                    deduped.append(item)
            return deduped
        return cleaned
    if isinstance(node, str) and key in LICENCE_TEXT_KEYS_V164:
        cleaned = clean_licence_review_v164(node)
        if cleaned != node:
            changes.append((node, cleaned))
        return cleaned
    return node


def _strip_text(node: Any, key: str = "") -> Any:
    """The document with every licence text field blanked, to compare the rest."""
    if isinstance(node, dict):
        return {k: _strip_text(v, k) for k, v in node.items()}
    if isinstance(node, list):
        if key in LICENCE_TEXT_KEYS_V164 and all(isinstance(item, str) for item in node):
            return []
        return [_strip_text(item, key) for item in node]
    if isinstance(node, str) and key in LICENCE_TEXT_KEYS_V164:
        return ""
    return node


def _clean_json(data: bytes) -> tuple[bytes, int]:
    original = json.loads(data)
    if (canonical_json(original) + "\n").encode("utf-8") != data:
        raise ValueError("download JSON is not in canonical form")
    changes: list[tuple[str, str]] = []
    cleaned = _clean_tree(original, "", changes)
    if _strip_text(cleaned) != _strip_text(original):
        raise ValueError("a non-licence field changed")
    return (canonical_json(cleaned) + "\n").encode("utf-8"), len(changes)


def _clean_csv(data: bytes) -> tuple[bytes, int]:
    text = data.decode("utf-8")
    bom = "﻿" if text.startswith("﻿") else ""
    rows = list(csv.reader(io.StringIO(text[len(bom):], newline="")))

    def write(table: list[list[str]]) -> bytes:
        stream = io.StringIO(newline="")
        csv.writer(stream).writerows(table)
        return (bom + stream.getvalue()).encode("utf-8")

    if write(rows) != data:
        raise ValueError("download CSV does not round-trip")
    if not rows or "license_code" not in rows[0]:
        return data, 0
    column = rows[0].index("license_code")
    changed = 0
    out = [rows[0]]
    for row in rows[1:]:
        if column < len(row):
            cleaned = clean_licence_review_v164(row[column])
            if cleaned != row[column]:
                changed += 1
                row = [*row[:column], cleaned, *row[column + 1:]]
        out.append(row)
    return write(out), changed


def run(check: bool) -> int:
    total = 0
    for iso3, base in COUNTRIES.items():
        catalog_path = base / "catalog.json"
        catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
        assets = {}
        for element in catalog["elements"]:
            for asset in element.get("downloadAssets") or []:
                if asset.get("format") == "ZIP":
                    assets[pathlib.PurePosixPath(asset["url"]).name] = asset
        touched = 0
        for zip_path in sorted((base / "downloads").glob("*.zip")):
            with zipfile.ZipFile(zip_path) as archive:
                members = {info.filename: archive.read(info.filename) for info in archive.infolist()}
            new_members: dict[str, bytes] = {}
            changes = 0
            for name, data in members.items():
                if name.endswith(".json"):
                    new_data, count = _clean_json(data)
                elif name.endswith(".csv"):
                    new_data, count = _clean_csv(data)
                else:
                    new_data, count = data, 0
                new_members[name] = new_data
                changes += count
            if changes == 0:
                continue
            touched += 1
            print(f"{iso3} {zip_path.name}: {changes} text field(s)")
            if check:
                continue
            body = zip_bytes(new_members.items())
            zip_path.write_bytes(body)
            asset = assets[zip_path.name]
            asset["byteSize"] = len(body)
            asset["sha256"] = hashlib.sha256(body).hexdigest()
            for entry in asset.get("entries") or []:
                data = new_members[entry["fileName"]]
                entry["byteSize"] = len(data)
                entry["sha256"] = hashlib.sha256(data).hexdigest()
        if touched and not check:
            catalog_path.write_text(json.dumps(catalog, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8")
        total += touched
    print(f"{'would change' if check else 'changed'} {total} ZIP(s)")
    return 1 if check and total else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="report the ZIPs that still carry a licence review")
    sys.exit(run(parser.parse_args().check))
