import type { ElementVisualizationSummaryV125 } from "./semanticTypesV125";

// Deterministically regenerated by tools/vietnam_semantic/build_semantic_v125.py.
export const ELEMENT_VISUALIZATION_SUMMARIES_V125: ElementVisualizationSummaryV125[] = [
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-001",
    "measureLabels": [
      "CPI 산출 원천 수",
      "CPI 순위",
      "CPI 순위(구 척도)",
      "CPI 신뢰구간 상한",
      "CPI 신뢰구간 하한",
      "CPI 점수",
      "CPI 점수(구 척도)",
      "CPI 표준오차"
    ],
    "noDataReason": null,
    "populatedRecordCount": 114,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 1997
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-002",
    "measureLabels": [
      "CPIA A. 경제관리 클러스터 평균",
      "CPIA B. 구조정책 클러스터 평균",
      "CPIA C. 사회적 포용",
      "CPIA D. 공공부문 관리",
      "CPIA IRAI 종합점수",
      "CPIA 공공부문 투명성",
      "CPIA 공공재원 배분의 형평성",
      "CPIA 공공행정의 질"
    ],
    "noDataReason": null,
    "populatedRecordCount": 312,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 1996
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-003",
    "measureLabels": [
      "1인당 GDP",
      "1인당 GDP 성장률",
      "GDP 성장률",
      "GDP 총액",
      "GNI 총액"
    ],
    "noDataReason": null,
    "populatedRecordCount": 272,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 1985
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-004",
    "measureLabels": [
      "극빈곤율",
      "빈곤율"
    ],
    "noDataReason": null,
    "populatedRecordCount": 29,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2022,
      "start": 1992
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-005",
    "measureLabels": [
      "산업구조"
    ],
    "noDataReason": null,
    "populatedRecordCount": 141,
    "primaryRenderer": "composition",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 1986
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-006",
    "measureLabels": [
      "전체 실업률",
      "청년 실업률"
    ],
    "noDataReason": null,
    "populatedRecordCount": 114,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 1991
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-007",
    "measureLabels": [
      "도시인구",
      "도시인구 증가율",
      "도시화율",
      "총인구"
    ],
    "noDataReason": null,
    "populatedRecordCount": 263,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 1960
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-008",
    "measureLabels": [
      "지니계수"
    ],
    "noDataReason": null,
    "populatedRecordCount": 13,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2022,
      "start": 1992
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-009",
    "measureLabels": [
      "GHG 배출 강도"
    ],
    "noDataReason": null,
    "populatedRecordCount": 90,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 1970
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-010",
    "measureLabels": [
      "가스별 배출량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 400,
    "primaryRenderer": "composition",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 1970
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-011",
    "measureLabels": [
      "부문별 배출량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 495,
    "primaryRenderer": "composition",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 1970
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-012",
    "measureLabels": [
      "LULUCF 순플럭스",
      "순 GHG 배출량",
      "총 GHG 배출량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 103,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 1970
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "typeOfInformation"
    ],
    "downloadAvailable": true,
    "elementId": "A-013",
    "measureLabels": [
      "NDC-SDG 연계",
      "NDC-SDG 연계 목록"
    ],
    "noDataReason": null,
    "populatedRecordCount": 365,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-014",
    "measureLabels": [
      "SDG Index 종합순위",
      "SDG Index 종합점수",
      "목표별 달성도"
    ],
    "noDataReason": null,
    "populatedRecordCount": 479,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 2000
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "detail_2",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-015",
    "measureLabels": [
      "SDG1 세부지표 달성도",
      "SDG10 세부지표 달성도",
      "SDG11 세부지표 달성도",
      "SDG12 세부지표 달성도",
      "SDG13 세부지표 달성도",
      "SDG14 세부지표 달성도",
      "SDG15 세부지표 달성도",
      "SDG16 세부지표 달성도"
    ],
    "noDataReason": null,
    "populatedRecordCount": 99,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2011
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-016",
    "measureLabels": [
      "1차 에너지 소비"
    ],
    "noDataReason": null,
    "populatedRecordCount": 427,
    "primaryRenderer": "composition",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 1965
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": false,
    "elementId": "A-017",
    "measureLabels": [
      "LCOE"
    ],
    "noDataReason": null,
    "populatedRecordCount": 72,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2050,
      "start": 2023
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-018",
    "measureLabels": [
      "발전 설비용량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 472,
    "primaryRenderer": "composition",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 2000
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-019",
    "measureLabels": [
      "송배전 손실률"
    ],
    "noDataReason": null,
    "populatedRecordCount": 34,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2023,
      "start": 1990
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-020",
    "measureLabels": [
      "재생에너지 비중"
    ],
    "noDataReason": null,
    "populatedRecordCount": 50,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 2000
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-021",
    "measureLabels": [
      "전력 접근률"
    ],
    "noDataReason": null,
    "populatedRecordCount": 84,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 1997
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-022",
    "measureLabels": [
      "MAIFI",
      "SAIDI",
      "SAIFI"
    ],
    "noDataReason": null,
    "populatedRecordCount": 39,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2015
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "capacityBand",
      "commissioningYear",
      "레코드 유형",
      "fuelType",
      "fuelTypeRaw"
    ],
    "downloadAvailable": true,
    "elementId": "A-023",
    "measureLabels": [
      "발전소 목록"
    ],
    "noDataReason": null,
    "populatedRecordCount": 1963,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "레코드 유형",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-024",
    "measureLabels": [
      "미공급 지역",
      "송전 선로 구간 수",
      "송전망 선로 목록"
    ],
    "noDataReason": null,
    "populatedRecordCount": 723,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2016,
      "start": 2016
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "레코드 유형",
      "type",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-025",
    "measureLabels": [
      "CCS 시설 목록",
      "CCS 시설 수",
      "상용 가동 CCS 시설 수"
    ],
    "noDataReason": null,
    "populatedRecordCount": 2,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2026,
      "start": 2026
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-026",
    "measureLabels": [
      "건물 풋프린트",
      "건물 풋프린트 레이어",
      "건물 풋프린트(OSM 참고)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 10,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2023
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-027",
    "measureLabels": [
      "도로 레이어",
      "철도 레이어"
    ],
    "noDataReason": null,
    "populatedRecordCount": 59,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2026,
      "start": 2026
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "레코드 유형",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-028",
    "measureLabels": [
      "기타 자연지형지물 목록",
      "내륙 수자원 지물 목록",
      "수로 레이어",
      "자연지형지물 레이어",
      "해안 지물 목록"
    ],
    "noDataReason": null,
    "populatedRecordCount": 7037,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2026,
      "start": 2026
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "레코드 유형",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-029",
    "measureLabels": [
      "FTA 건수",
      "FTA 체결 현황 목록",
      "무역협정 건수"
    ],
    "noDataReason": null,
    "populatedRecordCount": 31,
    "primaryRenderer": "policy-timeline",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2026
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-030",
    "measureLabels": [
      "[보조] 한-베트남 교역",
      "한-베트남 교역"
    ],
    "noDataReason": null,
    "populatedRecordCount": 141,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 1991
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-031",
    "measureLabels": [
      "물류성과지수(LPI)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 49,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2022,
      "start": 2007
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-032",
    "measureLabels": [
      "중간재 교역",
      "중간재 교역 규모"
    ],
    "noDataReason": null,
    "populatedRecordCount": 100,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2023,
      "start": 1995
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "A-033",
    "measureLabels": [
      "해운 연결성 지수(LSCI)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 82,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2006
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-001",
    "measureLabels": [
      "연 평년강수 (1991-2020 평년)",
      "연 평년기온 (1991-2020 평년)",
      "월 평년강수",
      "월 평년기온",
      "월별 건기/우기 구분(전국)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 38,
    "primaryRenderer": "seasonality",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 1991,
      "start": 1991
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "detail_2",
      "레코드 유형",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-002",
    "measureLabels": [
      "ADM1 단위 기간별 우세 기후대",
      "국가 우세 기후대",
      "기후대별 점유 면적",
      "기후대별 점유 비율",
      "열대기후(A군) 국토 점유 비율"
    ],
    "noDataReason": null,
    "populatedRecordCount": 1491,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2099,
      "start": 1930
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-003",
    "measureLabels": [
      "연강수량(관측)",
      "연평균 기온",
      "연평균 최고기온(관측)",
      "연평균 최저기온(관측)",
      "연평균기온(관측)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 12621,
    "primaryRenderer": "seasonality",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-004",
    "measureLabels": [
      "CMIP6 기반 과거／미래 기후(성×시나리오×연도 개체 목록)",
      "CMIP6 기반 과거／미래 기후(성×시나리오×연도 개체 목록) - 2025년 34개 체계",
      "CMIP6 기반 과거／미래 기후(성×시나리오×연도 개체 목록) - 2025년 34개 체계 - 월별 평년값(개편 후 ADM1 34개 체계)",
      "CMIP6 기반 과거／미래 기후(성×시나리오×연도 개체 목록) - 월별 평년값(ADM1, GADM 4.1)",
      "CMIP6 기반 과거／미래 기후(전국)",
      "CMIP6 기반 과거／미래 기후(전국) - 월별 평년값(전국)",
      "상대습도(hurs)",
      "연강수(pr)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 91596,
    "primaryRenderer": "scenario-range",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-005",
    "measureLabels": [
      "SPEI12",
      "가뭄(성×시나리오×연도 개체 목록)",
      "가뭄(성×시나리오×연도 개체 목록) - 2025년 34개 체계",
      "가뭄(성×시나리오×연도 개체 목록) - 2025년 34개 체계 - 월별 평년값(개편 후 ADM1 34개 체계)",
      "가뭄(성×시나리오×연도 개체 목록) - 월별 평년값(ADM1, GADM 4.1)",
      "가뭄(전국)",
      "가뭄(전국) - 월별 평년값(전국)",
      "연속 건조일수 CDD"
    ],
    "noDataReason": null,
    "populatedRecordCount": 54727,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2025,
      "start": 1991
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-006",
    "measureLabels": [
      "열대야 TR20",
      "열대야 TR23",
      "열대야 TR26",
      "열대야 TR29",
      "체감폭염 HI35",
      "폭염(성×시나리오×연도 개체 목록)",
      "폭염(성×시나리오×연도 개체 목록) - 2025년 34개 체계",
      "폭염(성×시나리오×연도 개체 목록) - 2025년 34개 체계 - 월별 평년값(개편 후 ADM1 34개 체계)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 80071,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-007",
    "measureLabels": [
      "연속 습윤일수 CWD",
      "최대 1일강수 RX1day",
      "최대 5일강수 RX5day",
      "호우일수 R20mm",
      "호우일수 R50mm",
      "홍수(성×시나리오×연도 개체 목록)",
      "홍수(성×시나리오×연도 개체 목록) - 2025년 34개 체계",
      "홍수(성×시나리오×연도 개체 목록) - 2025년 34개 체계 - 월별 평년값(개편 후 ADM1 34개 체계)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 80070,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-008",
    "measureLabels": [
      "상대해수면 Da Nang(중부 다낭) SSP1-1.9 17퍼센타일",
      "상대해수면 Da Nang(중부 다낭) SSP1-1.9 5퍼센타일",
      "상대해수면 Da Nang(중부 다낭) SSP1-1.9 83퍼센타일",
      "상대해수면 Da Nang(중부 다낭) SSP1-1.9 95퍼센타일",
      "상대해수면 Da Nang(중부 다낭) SSP1-1.9 중앙값",
      "상대해수면 Da Nang(중부 다낭) SSP1-2.6 17퍼센타일",
      "상대해수면 Da Nang(중부 다낭) SSP1-2.6 5퍼센타일",
      "상대해수면 Da Nang(중부 다낭) SSP1-2.6 83퍼센타일"
    ],
    "noDataReason": null,
    "populatedRecordCount": 1575,
    "primaryRenderer": "scenario-range",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "detail_2",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-009",
    "measureLabels": [
      "ND-GAIN 취약성",
      "WWF BRF",
      "WWF BRF 물리적 위험(Scape Physical)",
      "WWF BRF 제공 서비스(Provisioning)",
      "WWF BRF 조절",
      "WWF BRF 조절 서비스(Mitigating)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 255,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2026,
      "start": 2026
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "partial-records",
    "dimensionLabels": [
      "세부 분류",
      "detail_2",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-010",
    "measureLabels": [
      "2024년 최대 피해 극한기상 사건",
      "CRI 30년 누적 순위",
      "CRI 과거판 20년 누적 순위(구 방법론)",
      "CRI 과거판 20년 누적 점수(구 방법론)",
      "CRI 과거판 단년 순위(구 방법론)",
      "CRI 과거판 단년 점수(구 방법론)",
      "CRI 본문 수록 피해통계(2024년)",
      "CRI 순위"
    ],
    "noDataReason": null,
    "populatedRecordCount": 44,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 2012
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-011",
    "measureLabels": [
      "ND-GAIN 종합점수",
      "ND-GAIN 준비도",
      "물 하위지표",
      "보건 하위지표",
      "생태계 서비스 하위지표",
      "식량 하위지표",
      "인간 서식지 하위지표",
      "인프라 하위지표"
    ],
    "noDataReason": null,
    "populatedRecordCount": 1500,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 1995
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "partial-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-012",
    "measureLabels": [
      "사건 단위 위치정보 확보 현황",
      "연도별 자연재해 발생 건수",
      "재해",
      "재해 유형별 발생 건수",
      "재해 유형별 부상자",
      "재해 유형별 사망자",
      "재해 유형별 이재민",
      "재해 유형별 총피해액"
    ],
    "noDataReason": null,
    "populatedRecordCount": 275,
    "primaryRenderer": "policy-timeline",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "detail_2",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-013",
    "measureLabels": [
      "EU 평균 탄소지불액",
      "경제 노출지수(Economic Exposure Index)",
      "대EU 수출비중",
      "대EU 수출액",
      "무역 노출지수(Trade Exposure Index)",
      "생산 노출지수(Output Exposure Index)",
      "탄소지불액"
    ],
    "noDataReason": null,
    "populatedRecordCount": 33,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2022,
      "start": 2022
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-014",
    "measureLabels": [
      "GDP 변화율(기준선 대비)",
      "GDP 영향",
      "권고 탄소가격 경로",
      "누적 추가 세수",
      "배출 감소율",
      "배출 변화율(기준선 대비)",
      "세수 누적액",
      "연간 세수(GDP 대비) (범위 상한)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 12,
    "primaryRenderer": "scenario-range",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-015",
    "measureLabels": [
      "ETS 대상 시설 수",
      "국가 크레딧 메커니즘 상태",
      "국내 배출권거래제(ETS) 운영 상태",
      "국내 배출권거래제(ETS) 운영 상태(연도별 주요 단계)",
      "배출권 할당량",
      "탄소 가격(실효 가격)",
      "탄소세",
      "파리협정 제6조 협력 체결 현황"
    ],
    "noDataReason": null,
    "populatedRecordCount": 9,
    "primaryRenderer": "policy-timeline",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2020
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-016",
    "measureLabels": [
      "화석연료 소비 비중",
      "화석연료 소비 비중(EI 기반 보완 산출)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 35,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 1990
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-017",
    "measureLabels": [
      "가뭄 리스크",
      "가뭄 위험(Drought Risk)",
      "기준 물 스트레스",
      "기준 물스트레스 전망",
      "기준 물스트레스(Baseline Water Stress)",
      "물 스트레스 기여",
      "물 스트레스(SDG 6.4.2)",
      "물 스트레스(유역×성 개체 목록)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 4867,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-018",
    "measureLabels": [
      "1인당 GDP(PPP)",
      "1인당 GDP(PPP) 과거 실적(참고)",
      "1인당 GDP(PPP) 전 구간",
      "GDP(PPP)",
      "GDP(PPP) 과거 실적(참고)",
      "GDP(PPP) 전 구간",
      "GDP(PPP) 전망"
    ],
    "noDataReason": null,
    "populatedRecordCount": 282,
    "primaryRenderer": "scenario-range",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2100,
      "start": 1980
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-019",
    "measureLabels": [
      "인구 과거 실적(참고)",
      "인구 전 구간",
      "인구 전망"
    ],
    "noDataReason": null,
    "populatedRecordCount": 110,
    "primaryRenderer": "scenario-range",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2100,
      "start": 1950
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "detail_2",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-020",
    "measureLabels": [
      "INFORM Risk",
      "INFORM Risk 세계 순위",
      "INFORM Risk 시계열(2017–2026)",
      "INFORM Risk 위험등급",
      "INFORM 결측 지표 수",
      "INFORM 신뢰도 부족 지수",
      "INFORM 자료 최신성",
      "INFORM 추세"
    ],
    "noDataReason": null,
    "populatedRecordCount": 2695,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2017
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "detail_2",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-021",
    "measureLabels": [
      "GVI 7개 사회경제 차원 하위지수",
      "GVI 장래전망(PGVI, 2020–2100)",
      "GVI 취약성 지수",
      "구성지표",
      "전망 구성지표"
    ],
    "noDataReason": null,
    "populatedRecordCount": 2969,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2100,
      "start": 1990
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-022",
    "measureLabels": [
      "기후 투자 재원 구성",
      "기후 피해 GDP 손실(범위 상한)",
      "기후 피해 GDP 손실(범위 하한)",
      "적응 투자 필요액",
      "총 투자 필요액(적응+완화)",
      "추가 극빈곤 인구",
      "탈탄소 경로 투자 구성"
    ],
    "noDataReason": null,
    "populatedRecordCount": 8,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2050,
      "start": 2030
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-023",
    "measureLabels": [
      "건기 최저유량",
      "건기／우기 유량 차이 - 보조 지표(문헌값: MRC 2009",
      "건기／우기 유량 차이(하천 지점 개체 목록)",
      "메콩(Kratie) 건기",
      "메콩델타 건기 유량 비중",
      "메콩델타 우기 유량 비중",
      "우기 최고유량",
      "유역 단위 건우기 유량차(GIS 기반 산출)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 382,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-024",
    "measureLabels": [
      "관개농업 용수생산성 (SDG 6.4.1)",
      "농업 용수 비중 - 지역(ADM1) 배분 추정",
      "농업 용수 비중 - 지역(ADM1) 배분 추정 - 2025년 34개 체계",
      "농업 용수 취수 비중",
      "농업 용수 취수 비중(총 재생가능 수자원 대비)",
      "용수생산성",
      "지역(ADM1) 관개면적 - 배분 기준 원값",
      "지역(ADM1) 관개면적 - 배분 기준 원값 - 2025년 34개 체계"
    ],
    "noDataReason": null,
    "populatedRecordCount": 165,
    "primaryRenderer": "composition",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2023,
      "start": 1990
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "개체 구분(Basin／Country)"
    ],
    "downloadAvailable": true,
    "elementId": "B-025",
    "measureLabels": [
      "유역 면적",
      "유역 면적(HydroBASINS 기반 산출)",
      "유역 면적(베트남 국내분)",
      "유역 면적(유역 개체 목록)",
      "유역 총면적(국경 포함)",
      "전국 유역면적",
      "전국 유역면적 집계"
    ],
    "noDataReason": null,
    "populatedRecordCount": 120,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-026",
    "measureLabels": [
      "D8 유향 분포(격자 비율)",
      "대권역 우세 유향",
      "유향 D8 분포(성 단위 개체 목록)",
      "유향 D8 분포(성 단위 개체 목록) - 2025년 34개 체계",
      "유향 D8 분포(성 단위 개체 목록) - 유역 단위(HydroBASINS lvl6)",
      "유향(전국"
    ],
    "noDataReason": null,
    "populatedRecordCount": 165,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-027",
    "measureLabels": [
      "이용가능(정규 재생) 지하수",
      "지하수 자원량",
      "총 재생가능 지하수 자원량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 53,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 1990
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-028",
    "measureLabels": [
      "내부 재생가능 수자원(IRWR)",
      "메콩 연평균 유량 (범위 상한)",
      "메콩 연평균 유량 (범위 하한)",
      "수자원 국외 의존율",
      "외부 유입 수자원",
      "총 재생가능 수자원(TRWR)",
      "하천 유량",
      "하천 유량 - 기본 지표(GloFAS 지점 연평균, 10개국 공통 원천)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 25,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "partial-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-029",
    "measureLabels": [
      "맹그로브 면적",
      "맹그로브 면적 1996",
      "맹그로브 면적(MODIS)",
      "맹그로브 면적(WorldCover)",
      "산림 유형별 면적(전국)",
      "습윤열대 1차림 면적 2001(ADM1 단위 개체 목록)",
      "습윤열대 1차림 면적 2001(ADM1 단위 개체 목록) - Province/City (2025년 34개 체계)",
      "습윤열대 1차림 면적(위성 기준)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 483,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-030",
    "measureLabels": [
      "산림 이득",
      "산림 이득(전국)",
      "수관 이득(누적)",
      "수관 이득(연도별)",
      "조림지 연간 순증(대리지표)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 134,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "레코드 유형",
      "기간",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-031",
    "measureLabels": [
      "성(省)별 분석대상 면적",
      "성(省)별 수관 면적(2000)",
      "성(省)별 수관 면적(2010)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 294,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2010,
      "start": 2000
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "레코드 유형",
      "기간",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-032",
    "measureLabels": [
      "성(省)별 수관 피복률"
    ],
    "noDataReason": null,
    "populatedRecordCount": 292,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2010,
      "start": 2000
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "detail_2",
      "레코드 유형",
      "기간",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-033",
    "measureLabels": [
      "연간 수관 손실"
    ],
    "noDataReason": null,
    "populatedRecordCount": 6273,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2024,
      "start": 2001
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "detail_2",
      "레코드 유형",
      "기간",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-034",
    "measureLabels": [
      "산림탄소 순플럭스(누계)",
      "산림탄소 순플럭스(연평균)",
      "산림탄소 총배출(누계)",
      "산림탄소 총배출(연간)",
      "산림탄소 총배출(연평균)",
      "산림탄소 총흡수(누계)",
      "산림탄소 총흡수(연평균)",
      "수관 면적"
    ],
    "noDataReason": null,
    "populatedRecordCount": 1739,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2024,
      "start": 2000
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "레코드 유형",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-035",
    "measureLabels": [
      "1인당 경작지 면적",
      "가경지 비율(농지 대비)",
      "경작지 비율(농지 대비)",
      "경작지 비율(육지면적 대비)",
      "관개 정비면적 비율(경작지 대비)",
      "농업 총면적(Agriculture)",
      "농지 단위면적당 농업생산액",
      "농지 비율(육지면적 대비)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 3998,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 1961
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "레코드 유형",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-036",
    "measureLabels": [
      "토지이용 변화율",
      "토지피복 기반 변화율(성×기간 개체 목록)",
      "토지피복 기반 변화율(성×기간 개체 목록) - 2025년 34개 체계",
      "토지피복 기반 변화율(전국, 성 합계)",
      "토지피복 변화율",
      "토지피복 변화율(MODIS)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 440,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 2020
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-037",
    "measureLabels": [
      "토지피복 면적",
      "토지피복 면적(CGLS)",
      "토지피복 면적(MODIS)",
      "토지피복 면적(WorldCover)",
      "토지피복 분류별 면적(성 단위 개체 목록)",
      "토지피복 분류별 면적(성 단위 개체 목록) - 2025년 34개 체계",
      "토지피복 분류별 면적(전국)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 781,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-038",
    "measureLabels": [
      "1인당 도시폐기물 발생량",
      "[산출 투입",
      "농업잔재 자원량",
      "도시폐기물 발생량",
      "도시폐기물 수거율(참고)",
      "도시폐기물 중 유기성 자원량(산출)",
      "도시폐기물 중 음식물",
      "도시폐기물 처리경로별 비중"
    ],
    "noDataReason": null,
    "populatedRecordCount": 399,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2050,
      "start": 1965
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-039",
    "measureLabels": [
      "PDP8 개정 2030 목표 (범위 상한)",
      "PDP8 개정 2030 목표 (범위 하한)",
      "개발 완료 잠재량",
      "개발가능 잠재량(EVN 기준) (범위 상한)",
      "개발가능 잠재량(EVN 기준) (범위 하한)",
      "경제적 잠재량 (범위 상한)",
      "경제적 잠재량 (범위 하한)",
      "기술적 잠재량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 263,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-040",
    "measureLabels": [
      "기술 잠재량",
      "발전 잠재량 (범위 상한)",
      "발전 잠재량 (범위 하한)",
      "심도 1km 지온",
      "심도 2km 지온",
      "심도 3km 지온",
      "심도별 지온(성 단위 개체 목록)",
      "심도별 지온(성 단위 개체 목록) - 2025년 34개 체계"
    ],
    "noDataReason": null,
    "populatedRecordCount": 199,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-041",
    "measureLabels": [
      "PVOUT 계절변동지수",
      "PVOUT 계절변동지수 (범위 상한)",
      "PVOUT 계절변동지수 (범위 하한)",
      "기온(TEMP, PV 성능 보정용)",
      "산란 일사량(DIF)",
      "수평면 전일사량",
      "수평면 전일사량(GHI)",
      "실용 발전량 잠재"
    ],
    "noDataReason": null,
    "populatedRecordCount": 147,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-042",
    "measureLabels": [
      "평균 풍속(100m)",
      "풍력 에너지 장미도(방위별 에너지 비중)",
      "풍력 에너지밀도(100m)",
      "풍력 자원",
      "풍력 자원(성 단위 개체 목록) (기준연도 2017)",
      "풍력 자원(성 단위 개체 목록) (기준연도 2017) - 2025년 34개 체계",
      "풍력 자원(전국) (기준연도 2017)",
      "풍속 장미도(방위별 평균풍속 비중)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 533,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "detail_2",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-043",
    "measureLabels": [
      "가채연수(R/P ratio)",
      "가채연수(R/P)",
      "석유 확인매장량",
      "석유 확인매장량(질량 기준)",
      "석탄 생산량",
      "석탄 확인매장량",
      "세계 확인매장량 비중",
      "원유 생산량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 127,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 1980
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "레코드 유형",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-044",
    "measureLabels": [
      "10개국 기준광물 목록",
      "원광 수출규제 대상 광종",
      "핵심광물 법",
      "핵심광물 부존 상태",
      "핵심광물 부존 상태 - 광종별 레코드(기준 광물 20종 + 기타)",
      "핵심광물 수출규제 체계(일반) - 광종별 수출규제 여부는 1.2 레코드 열 참조",
      "현지조사 결과 반영"
    ],
    "noDataReason": null,
    "populatedRecordCount": 23,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2024
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "B-045",
    "measureLabels": [
      "세계 매장량 비중",
      "세계 매장량 순위",
      "세계 생산량 비중",
      "세계 생산량 순위",
      "인용 쪽"
    ],
    "noDataReason": null,
    "populatedRecordCount": 224,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 2019
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-046",
    "measureLabels": [
      "핵심광물 매장량 미수록(리튬",
      "확인",
      "확인 매장량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 64,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-047",
    "measureLabels": [
      "광산 생산량",
      "생산량 미수록(구리",
      "연간 생산량 - 광종별 레코드(국가×광종×연도)",
      "희토류 생산 급감(2024→2025) 사유"
    ],
    "noDataReason": null,
    "populatedRecordCount": 81,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "B-048",
    "measureLabels": [
      "광산 경도",
      "광산 위도",
      "광종별 주요 광산 수",
      "주요 광산 위치(개체 목록)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 41,
    "primaryRenderer": "spatial-summary",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-001",
    "measureLabels": [
      "2b. BAU 2030 부문별 배출량 (5개 부문)",
      "BAU 배출 시나리오 (총량, 2014~2030 시계열)",
      "NDC (국가 온실가스 감축 목표)",
      "NDC-SDG 연계",
      "기준정보 (기준연도",
      "무조건부 감축목표 (Unconditional Contribution, 2030)",
      "원본 링크 (URL)",
      "이행 재원 수요 (적응 부문"
    ],
    "noDataReason": null,
    "populatedRecordCount": 110,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-002",
    "measureLabels": [
      "2016년 부문×가스별 GHG 배출량",
      "BTR (격년투명성보고서, 舊 BUR)",
      "GHG 순배출량 (incl. LULUCF)",
      "GHG 총배출량 (excl. LULUCF)",
      "가스 종류별 배출량 (2016, 순배출 기준)",
      "관측 기후변화 추세 (실측)",
      "기후 시나리오 전망 (SSP)",
      "기후변화 경제적 손실 전망"
    ],
    "noDataReason": null,
    "populatedRecordCount": 34,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-003",
    "measureLabels": [
      "NAP (국가 적응 계획)",
      "기후변화 취약성 평가 (부문별 위험도)",
      "모니터링",
      "부문별 취약성 평가 커버리지",
      "수립 목적 및 법적 근거",
      "원문 문서 정보",
      "이해관계자 참여 및 젠더",
      "이행 단계"
    ],
    "noDataReason": null,
    "populatedRecordCount": 272,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-004",
    "measureLabels": [
      "2030년 부문별 감축 경로 (NCCS 중간목표)",
      "2050년 부문별 감축 경로 (넷제로 경로)",
      "LT-LEDS (장기 저탄소 발전 전략)",
      "공정전환(Just Transition) 및 국제 이니셔티브",
      "넷제로 목표 및 배출 정점",
      "부문별 탈탄소 전략 (7대 부문 주요 조치)",
      "산림피복 목표",
      "에너지 전환 목표 (재생에너지"
    ],
    "noDataReason": null,
    "populatedRecordCount": 71,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-005",
    "measureLabels": [
      "TNA (기술 수요 평가)",
      "감축 TAP(기술실행계획) 구조",
      "감축 부문별 기술이전 장벽",
      "감축 우선기술 MCDA 평가점수",
      "감축 우선기술 목록 (에너지",
      "감축 우선부문 평가 매트릭스",
      "감축(Mitigation) 부문 우선순위 선정 (기준",
      "결론 및 향후 전망"
    ],
    "noDataReason": null,
    "populatedRecordCount": 408,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-006",
    "measureLabels": [
      "UNFCCC 국제 등록부 연동 현황",
      "국내 이행 법적 근거 (파리협정 제6.2조",
      "국내 탄소 레지스트리",
      "상응조정(Corresponding Adjustment, CA) 체계",
      "원본 링크 (URL)",
      "제6.2조 ITMO 이전실적 (Transfer)",
      "제6.2조 양자협력(ITMO) 협정 체결 현황",
      "제6.4조(PACM) 이행"
    ],
    "noDataReason": null,
    "populatedRecordCount": 38,
    "primaryRenderer": "capability-scorecard",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-007",
    "measureLabels": [
      "NMA 플랫폼 전체 현황 (글로벌 참고지표, GCNMA-8 기준)",
      "NMA별 참여 지위",
      "베트남 참여 현황",
      "베트남 참여 현황 (Art 6.8 NMA 등록",
      "원본 링크 (URL)",
      "참여 상태 코드 체계",
      "파리협정 제6.8조 비시장 접근법 참여 현황",
      "플랫폼 역량강화 활동 (글로벌 참고지표, Vietnam 특정 언급 없음)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 7,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "[이니셔티브] 운영 상태"
    ],
    "downloadAvailable": true,
    "elementId": "C-008",
    "measureLabels": [
      "Cooperative Climate Initiative 참여 현황",
      "NAZCA 등재 개별 행위자 명부",
      "NAZCA 등재 행위자",
      "NAZCA 참여형태(Engagement) 집계",
      "UNFCCC Party 주요 일자",
      "개별 행위자 목록 확보 가능성",
      "기후 분야 (감축 / 적응)",
      "원본 링크 (URL)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 117,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-009",
    "measureLabels": [
      "GHG 감축 시행령 규정 내용 (Decree 06/2022",
      "GHG 인벤토리 대상",
      "국가기후변화전략 2050",
      "기후 법제도 현황",
      "대상 분야 (감축 / 적응 / 에너지 / 산업)",
      "법령 제",
      "법령 제정",
      "법령명"
    ],
    "noDataReason": null,
    "populatedRecordCount": 19,
    "primaryRenderer": "policy-timeline",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-010",
    "measureLabels": [
      "기타 환경 관련 법제도 현황",
      "대기",
      "법제 개정 현황",
      "법제 목록 개요 (환경보호 관련 법령",
      "생물다양성 법제 (생물다양성법 20/2008/QH12 + 국가생물다양성전략 2030)",
      "생산자책임재활용(EPR) 제도",
      "생산자책임재활용(EPR) 제도 (LEP 제54",
      "수자원법 (Law on Water Resources, 28/2023/QH15)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 19,
    "primaryRenderer": "policy-timeline",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-011",
    "measureLabels": [
      "범죄 통계 (정량지표)",
      "베트남 여행경보 현황 및 해외 비교",
      "베트남 현지 긴급신고 번호",
      "성 단위 치안지표",
      "성 단위 치안지표 공표 여부",
      "여행경보 등급 체계 (외교부 4단계 정의)",
      "원본 링크 (URL)",
      "재외공관 연락처"
    ],
    "noDataReason": null,
    "populatedRecordCount": 38,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-012",
    "measureLabels": [
      "PPP 법률 유무",
      "PPP 법제도",
      "PPP 전담 기관",
      "PPP 프로젝트 이력 (건수)",
      "VfM(Value for Money) 평가 의무 여부",
      "계약 유형 (BOT / BOO / Concession 등)",
      "법령 제",
      "분쟁해결"
    ],
    "noDataReason": null,
    "populatedRecordCount": 20,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-013",
    "measureLabels": [
      "(참고) 소액투자자 보호",
      "(참고) 창업 소요일수",
      "(참고) 창업 절차 수",
      "FTA 건수",
      "미-베트남 BIT 체결 여부",
      "발효 BIT 건수",
      "법인세 50% 감면기간",
      "법인세 면제기간"
    ],
    "noDataReason": null,
    "populatedRecordCount": 129,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-014",
    "measureLabels": [
      "건축 허가 절차",
      "데이터 출처 및 산정 방법",
      "원본 링크 (URL)",
      "인허가 유형별 비교 (절차 수",
      "인허가 프로세스",
      "전력 사업 허가 절차",
      "토지 취득 절차",
      "품질"
    ],
    "noDataReason": null,
    "populatedRecordCount": 46,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-015",
    "measureLabels": [
      "재생에너지 법제도 원본 링크",
      "정책 문서 원본 링크 레지스트리",
      "지정 출처 상태 및 데이터 보완 이력"
    ],
    "noDataReason": null,
    "populatedRecordCount": 24,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "레코드 유형",
      "기간"
    ],
    "downloadAvailable": true,
    "elementId": "C-016",
    "measureLabels": [
      "바이오매스발전(điện sinh khối) 계획용량",
      "소수력(thủy điện nhỏ) 계획용량",
      "수력 30MW초과~50MW미만 계획용량",
      "양수발전(thủy điện tích năng) 계획용량",
      "옥상태양광(ĐMT mái nhà) 계획용량",
      "육상 근해 풍력(điện gió trên bờ và gần bờ) 계획용량",
      "집중형 태양광(ĐMT tập trung) 계획용량",
      "폐기물발전(điện rác) 계획용량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 1416,
    "primaryRenderer": "policy-timeline",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-017",
    "measureLabels": [
      "미도입 인센티브 유형",
      "성별 재생에너지 지원제도",
      "인센티브 유형",
      "인센티브 조건 (가격 / 기간 / 용량)",
      "재생에너지 투자 인센티브"
    ],
    "noDataReason": null,
    "populatedRecordCount": 56,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-018",
    "measureLabels": [
      "RE 비중 목표",
      "도매 전력시장 가격 공표",
      "발전 설비 확충 계획",
      "실적 전력가격",
      "에너지 수요 전망",
      "전력 수요 성장률",
      "전력 수출입 계획",
      "전력부문 온실가스(GHG) 배출 전망"
    ],
    "noDataReason": null,
    "populatedRecordCount": 69,
    "primaryRenderer": "scenario-range",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-019",
    "measureLabels": [
      "C-019",
      "C-019 ①",
      "C-019 ②",
      "C-019 ③",
      "C-019 ④",
      "ETS 유연성",
      "MRV(모니터링",
      "법적 근거 체계 (모법"
    ],
    "noDataReason": null,
    "populatedRecordCount": 56,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "status-only",
    "dataPresenceStatus": "not-collected",
    "dimensionLabels": [],
    "downloadAvailable": false,
    "elementId": "C-020",
    "measureLabels": [],
    "noDataReason": "not-collected",
    "populatedRecordCount": 0,
    "primaryRenderer": "status-only",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "status-only",
    "dataPresenceStatus": "not-collected",
    "dimensionLabels": [],
    "downloadAvailable": false,
    "elementId": "C-021",
    "measureLabels": [],
    "noDataReason": "not-collected",
    "populatedRecordCount": 0,
    "primaryRenderer": "status-only",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-022",
    "measureLabels": [
      "ETS 시범사업 로드맵",
      "MRV(모니터링",
      "배출허용총량(배출예산)",
      "법적",
      "상쇄배출권(오프셋) 적격기준",
      "소관기관",
      "수집 상태 및 보완 경로",
      "시장 규제 및 시장설계"
    ],
    "noDataReason": null,
    "populatedRecordCount": 61,
    "primaryRenderer": "capability-scorecard",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "status-only",
    "dataPresenceStatus": "not-collected",
    "dimensionLabels": [],
    "downloadAvailable": false,
    "elementId": "C-023",
    "measureLabels": [],
    "noDataReason": "not-collected",
    "populatedRecordCount": 0,
    "primaryRenderer": "status-only",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-024",
    "measureLabels": [
      "FREL/FRL 제출 여부",
      "RBP 검증 배출감축량",
      "REDD+ 결과기반지불",
      "REDD+ 국가전략 수립 여부",
      "REDD+ 현황",
      "세이프가드 정보시스템(SIS) 구축 여부",
      "수정 FRL 값",
      "참여 기금"
    ],
    "noDataReason": null,
    "populatedRecordCount": 13,
    "primaryRenderer": "capability-scorecard",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "C-025",
    "measureLabels": [
      "CDM 크레딧 소각량",
      "GCC 등록 심사중 프로젝트 수",
      "GCC 등록 프로젝트 검증 연간 감축량 합계",
      "GCC 등록 프로젝트 수",
      "Gold Standard 등록 프로젝트 수",
      "Gold Standard 연간 예상 크레딧 합계",
      "Gold Standard 인증 완료",
      "JCM 등록 프로젝트 수"
    ],
    "noDataReason": null,
    "populatedRecordCount": 1190,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "detail_2",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-001",
    "measureLabels": [
      "단위 사업당 CAPEX"
    ],
    "noDataReason": null,
    "populatedRecordCount": 14,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 2024
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-002",
    "measureLabels": [
      "시장 성장률"
    ],
    "noDataReason": null,
    "populatedRecordCount": 56,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2030,
      "start": 2000
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "레코드 유형",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-003",
    "measureLabels": [
      "예상 감축량"
    ],
    "noDataReason": null,
    "populatedRecordCount": 464,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 2023
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-004",
    "measureLabels": [
      "크레딧 가격 연동 수익성"
    ],
    "noDataReason": null,
    "populatedRecordCount": 15,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2026
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-005",
    "measureLabels": [
      "감축/적응 구분별 예산 배분 비율"
    ],
    "noDataReason": null,
    "populatedRecordCount": 8,
    "primaryRenderer": "multi-metric-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2020,
      "start": 2010
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-006",
    "measureLabels": [
      "기후 관련 조세 수입"
    ],
    "noDataReason": null,
    "populatedRecordCount": 276,
    "primaryRenderer": "multi-metric-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 1995
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-007",
    "measureLabels": [
      "기후예산태깅(CBT)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 3,
    "primaryRenderer": "multi-metric-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2022,
      "start": 2015
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-008",
    "measureLabels": [
      "주관 부처별 기후 예산 규모"
    ],
    "noDataReason": null,
    "populatedRecordCount": 14,
    "primaryRenderer": "multi-metric-trend",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2020,
      "start": 2012
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-009",
    "measureLabels": [
      "D-009_environmental_protection_expenditure_lcu",
      "D-009_environmental_protection_expenditure_pct_gdp",
      "기후대응 정부 예산"
    ],
    "noDataReason": null,
    "populatedRecordCount": 7,
    "primaryRenderer": "multi-metric-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2020,
      "start": 2013
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-010",
    "measureLabels": [
      "화석연료 보조금 규모"
    ],
    "noDataReason": null,
    "populatedRecordCount": 10,
    "primaryRenderer": "multi-metric-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 2020
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "기술",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-011",
    "measureLabels": [
      "개도국 내 각국별 ODA 규모"
    ],
    "noDataReason": null,
    "populatedRecordCount": 354,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 2020
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-012",
    "measureLabels": [
      "경쟁국 민간기업의 개도국 진출 현황"
    ],
    "noDataReason": null,
    "populatedRecordCount": 1168,
    "primaryRenderer": "category-comparison",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-013",
    "measureLabels": [
      "GGGI Green Growth Index"
    ],
    "noDataReason": null,
    "populatedRecordCount": 24,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2024
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-014",
    "measureLabels": [
      "EDCF 프로젝트"
    ],
    "noDataReason": null,
    "populatedRecordCount": 168,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-015",
    "measureLabels": [
      "ODA Korea 프로젝트"
    ],
    "noDataReason": null,
    "populatedRecordCount": 1050,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-016",
    "measureLabels": [
      "지자체"
    ],
    "noDataReason": null,
    "populatedRecordCount": 632,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-017",
    "measureLabels": [
      "한국 ODA 기관 PCP/입찰 현황"
    ],
    "noDataReason": null,
    "populatedRecordCount": 305,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "세부 분류",
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-018",
    "measureLabels": [
      "Adaptation Fund 프로젝트"
    ],
    "noDataReason": null,
    "populatedRecordCount": 8,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "기술분야"
    ],
    "downloadAvailable": true,
    "elementId": "D-019",
    "measureLabels": [
      "CTCN 기술지원 요청"
    ],
    "noDataReason": null,
    "populatedRecordCount": 10,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-020",
    "measureLabels": [
      "GCF 승인 프로젝트 건수",
      "GCF 승인 프로젝트 레지스트리",
      "GCF 승인액 총계"
    ],
    "noDataReason": null,
    "populatedRecordCount": 9,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-021",
    "measureLabels": [
      "주요 국제기구"
    ],
    "noDataReason": null,
    "populatedRecordCount": 640,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-022",
    "measureLabels": [
      "MDB",
      "MDB/DFI/PPP 투자 프로젝트"
    ],
    "noDataReason": null,
    "populatedRecordCount": 247,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "레코드 유형",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-023",
    "measureLabels": [
      "ODA 및 기후기금 재원"
    ],
    "noDataReason": null,
    "populatedRecordCount": 114,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": 2025,
      "start": 2025
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "레코드 유형",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "D-024",
    "measureLabels": [
      "VC"
    ],
    "noDataReason": null,
    "populatedRecordCount": 27,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2026
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-025",
    "measureLabels": [
      "민간 인프라 투자(PPI)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 173,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "D-026",
    "measureLabels": [
      "MIGA 정치적 리스크 보증"
    ],
    "noDataReason": null,
    "populatedRecordCount": 13,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "orgCategory"
    ],
    "downloadAvailable": true,
    "elementId": "E-001",
    "measureLabels": [
      "CTCN NDE(국가지정기구)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 18,
    "primaryRenderer": "directory",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "a64Status",
      "레코드 유형",
      "recordStatus"
    ],
    "downloadAvailable": true,
    "elementId": "E-002",
    "measureLabels": [
      "DNA(국가지정기관)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 46,
    "primaryRenderer": "directory",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "role"
    ],
    "downloadAvailable": true,
    "elementId": "E-003",
    "measureLabels": [
      "GCF NDA(국가지정기관)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 8,
    "primaryRenderer": "directory",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "city",
      "collectionStatus",
      "contactType",
      "레코드 유형",
      "orgType",
      "recordStatus"
    ],
    "downloadAvailable": true,
    "elementId": "E-004",
    "measureLabels": [
      "국제기구 현지사무소 담당자"
    ],
    "noDataReason": null,
    "populatedRecordCount": 19,
    "primaryRenderer": "directory",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "city",
      "레코드 유형",
      "orgType",
      "국제협력 실적 구분"
    ],
    "downloadAvailable": true,
    "elementId": "E-005",
    "measureLabels": [
      "대학"
    ],
    "noDataReason": null,
    "populatedRecordCount": 20,
    "primaryRenderer": "directory",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "amountStatus",
      "amountType",
      "city",
      "collectionStatus",
      "레코드 유형",
      "fundOrAffiliate",
      "hqCountryIso3",
      "investSector"
    ],
    "downloadAvailable": true,
    "elementId": "E-006",
    "measureLabels": [
      "현지 투자자 네트워크"
    ],
    "noDataReason": null,
    "populatedRecordCount": 15,
    "primaryRenderer": "directory",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "분류",
      "레코드 유형",
      "부문별 Tier",
      "표준 분류",
      "확인 상태 구분"
    ],
    "downloadAvailable": true,
    "elementId": "E-007",
    "measureLabels": [
      "BTR(격년투명성보고서) 제출 이력",
      "CBIT(투명성역량강화이니셔티브) 지원 수혜 여부",
      "GHG 인벤토리 작성 역량(Tier)",
      "MRV 제도",
      "국가 인벤토리",
      "제3자 검증 체계 보유 여부"
    ],
    "noDataReason": null,
    "populatedRecordCount": 22,
    "primaryRenderer": "capability-scorecard",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "연도"
    ],
    "downloadAvailable": false,
    "elementId": "E-008",
    "measureLabels": [
      "논문",
      "논문,특허"
    ],
    "noDataReason": null,
    "populatedRecordCount": 6791,
    "primaryRenderer": "document-library",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2026,
      "start": 2026
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "partial-records",
    "dimensionLabels": [
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "E-009",
    "measureLabels": [
      "STEM 졸업 비중(남성)",
      "STEM 졸업 비중(여성)",
      "STEM 졸업 비중(전체)",
      "STEM 졸업자 수(절대수)",
      "연구자 수(백만명당)",
      "연구자 수(절대수)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 38,
    "primaryRenderer": "kpi-trend",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2023,
      "start": 2002
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "E-010",
    "measureLabels": [
      "GERD",
      "GII 2025"
    ],
    "noDataReason": null,
    "populatedRecordCount": 185,
    "primaryRenderer": "score-benchmark",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 2002
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "세부 분류",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "E-011",
    "measureLabels": [
      "NRI 2025",
      "기술준비수준(TRL)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 50,
    "primaryRenderer": "capability-scorecard",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2025,
      "start": 2021
    }
  },
  {
    "contractStatus": "specialized",
    "dataPresenceStatus": "partial-records",
    "dimensionLabels": [
      "분류체계",
      "통화",
      "직군",
      "성별",
      "source",
      "연도"
    ],
    "downloadAvailable": true,
    "elementId": "E-012",
    "measureLabels": [
      "고용 구성비",
      "고용률",
      "직군 내 여성 비중",
      "직군별 월평균 임금",
      "직군별 종사자 수",
      "총 취업자 수",
      "평균 월임금"
    ],
    "noDataReason": null,
    "populatedRecordCount": 2158,
    "primaryRenderer": "paired-category-comparison",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2024,
      "start": 1996
    }
  },
  {
    "contractStatus": "status-only",
    "dataPresenceStatus": "no-populated-record",
    "dimensionLabels": [],
    "downloadAvailable": false,
    "elementId": "E-013",
    "measureLabels": [
      "A/S 인프라(서비스센터",
      "과거 유사시설 O&M 실적",
      "부품 조달 가능성(국내생산/수입의존)",
      "숙련 기술인력 가용성(등급)",
      "예방정비 체계 수준(등급)"
    ],
    "noDataReason": "schema-only",
    "populatedRecordCount": 0,
    "primaryRenderer": "status-only",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "agreementType",
      "레코드 유형",
      "status",
      "문서 유형",
      "협력 상대 구분"
    ],
    "downloadAvailable": true,
    "elementId": "E-014",
    "measureLabels": [
      "양자협정 현황"
    ],
    "noDataReason": null,
    "populatedRecordCount": 10,
    "primaryRenderer": "policy-timeline",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형"
    ],
    "downloadAvailable": true,
    "elementId": "E-015",
    "measureLabels": [
      "NDC Partnership 회원 여부"
    ],
    "noDataReason": null,
    "populatedRecordCount": 4,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "referenceYear",
      "부문"
    ],
    "downloadAvailable": false,
    "elementId": "E-016",
    "measureLabels": [
      "한국 기후기술 TRL(분야별 기술수준"
    ],
    "noDataReason": null,
    "populatedRecordCount": 4,
    "primaryRenderer": "capability-scorecard",
    "spatiallyLinked": false,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "연도"
    ],
    "downloadAvailable": false,
    "elementId": "E-017",
    "measureLabels": [
      "기후기술 수준 순위",
      "기후기술 수준(최고국 대비)"
    ],
    "noDataReason": null,
    "populatedRecordCount": 10,
    "primaryRenderer": "evidence-matrix",
    "spatiallyLinked": false,
    "yearRange": {
      "end": 2020,
      "start": 2020
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "좌표 구분"
    ],
    "downloadAvailable": true,
    "elementId": "E-018",
    "measureLabels": [
      "국내 기업 개도국 진출 현황"
    ],
    "noDataReason": null,
    "populatedRecordCount": 36,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "city",
      "레코드 유형",
      "기후·에너지 담당 판정",
      "행 유형"
    ],
    "downloadAvailable": true,
    "elementId": "E-019",
    "measureLabels": [
      "개도국 내 한국 기관 사무소"
    ],
    "noDataReason": null,
    "populatedRecordCount": 9,
    "primaryRenderer": "directory",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  },
  {
    "contractStatus": "archetype",
    "dataPresenceStatus": "actual-records",
    "dimensionLabels": [
      "레코드 유형",
      "supportType",
      "금액 종류",
      "신청시기 구분",
      "지원 유형 표준",
      "지원대상 구분"
    ],
    "downloadAvailable": true,
    "elementId": "E-020",
    "measureLabels": [
      "한국 공공",
      "한국 공공 기후기술 지원사업 예산 규모"
    ],
    "noDataReason": null,
    "populatedRecordCount": 7,
    "primaryRenderer": "portfolio",
    "spatiallyLinked": true,
    "yearRange": {
      "end": null,
      "start": null
    }
  }
];
